* crossval_nma_vs_r.do - Cross-validation: Stata nma vs R netmeta
*
* Compares treatment effect estimates against R netmeta 3.3-1 benchmarks.
* Equivalence: nma_fit (multivariate REML) ~ netmeta() (graph-theoretical REML)
*
* Datasets:
*   CV1: Senn 2013 — Glucose-lowering drugs, 26 studies, 10 treatments (MD)
*   CV2: Dogliotti 2014 — Anticoagulants in AF, 20 studies, 8 treatments (logOR)
*
* Companion: 01_r_netmeta.R (run first to regenerate benchmarks)
*   library(netmeta); netmeta(TE, seTE, treat1, treat2, studlab, ...)
*   REML random-effects, reference = Placebo
*
* tau2 differences:
*   R netmeta uses graph-theoretical REML (Rucker 2012).
*   Stata nma uses multivariate REML. Treatment effects converge (all within
*   0.04 except Benfluorex at 0.096, which has only 2 studies).
*
* Signs: R reports Placebo vs Treatment (positive = treatment better).
*   Stata reports Treatment vs Placebo (negative = treatment better).
*   All comparisons use absolute values.
*
* Tolerance: 0.05 for PASS, 0.10 for NOTE, >0.10 = FAIL
*   tau2 rows are informational only (method differences expected)
*
* Produces: crossval_nma_vs_r.xlsx
* Location: ~/Stata-Tools/nma/qa/
* Run: stata-mp -b do qa/crossval_nma_vs_r.do
* Date: 2026-03-13

clear all
set more off
version 16.0
set varabbrev off

local test_count = 0
local pass_count = 0
local fail_count = 0

local pkg_dir "/home/tpcopeland/Stata-Tools/nma"
local qa_dir "`pkg_dir'/qa"
local outfile "`qa_dir'/crossval_nma_vs_r.xlsx"

capture ado uninstall nma
adopath ++ "`pkg_dir'"


* ============================================================
* R netmeta benchmarks (netmeta 3.3-1, REML, ref=Placebo)
* Generated by 01_r_netmeta.R — absolute values of coefficients
* ============================================================

* Senn 2013 — |MD| vs Placebo
local r_s_Acarbose       = 0.8582
local r_s_Benfluorex     = 0.7395
local r_s_Metformin      = 1.1315
local r_s_Miglitol       = 0.9500
local r_s_Pioglitazone   = 1.1308
local r_s_Rosiglitazone  = 1.2351
local r_s_Sitagliptin    = 0.5700
local r_s_Sulfonylurea   = 0.4247
local r_s_Vildagliptin   = 0.7000
local r_s_tau2           = 0.0963

* Dogliotti 2014 — |logOR| vs Placebo
* Note: WASPO_2007 (0/36 vs 0/39) dropped by netmeta (undefined logOR)
local r_d_Apixaban  = 1.1025
local r_d_ASA       = 0.2704
local r_d_ASA_Clop  = 0.5233
local r_d_Dab110    = 0.9656
local r_d_Dab150    = 1.3219
local r_d_Rivarox   = 1.1362
local r_d_VKA       = 0.8857
local r_d_tau2      = 0.0163

* Cross-validation tolerance: 0.05 for coefficients
local tol = 0.05
local tol_note = 0.10


* ============================================================
* CV1: Senn 2013 — Glucose-lowering drugs (HbA1c MD)
* 26 studies, 10 treatments, pre-computed contrasts
* ============================================================

clear
input str20 study str15 treat1 str15 treat2 double(te se_te)
"DeFronzo1995"      "Metformin"     "Placebo"       -1.90  0.1414
"Lewin2007"         "Metformin"     "Placebo"       -0.82  0.0992
"Willms1999a"       "Metformin"     "Acarbose"      -0.20  0.3579
"Davidson2007"      "Rosiglitazone" "Placebo"       -1.34  0.1435
"Wolffenbuttel1999" "Rosiglitazone" "Placebo"       -1.10  0.1141
"Kipnes2001"        "Pioglitazone"  "Placebo"       -1.30  0.1268
"Kerenyi2004"       "Rosiglitazone" "Placebo"       -0.77  0.1078
"Hanefeld2004"      "Pioglitazone"  "Metformin"      0.16  0.0849
"Derosa2004"        "Pioglitazone"  "Rosiglitazone"  0.10  0.1831
"Baksi2004"         "Rosiglitazone" "Placebo"       -1.30  0.1014
"Rosenstock2008"    "Rosiglitazone" "Placebo"       -1.09  0.2263
"Zhu2003"           "Rosiglitazone" "Placebo"       -1.50  0.1624
"Yang2003"          "Rosiglitazone" "Metformin"     -0.14  0.2239
"Vongthavaravat02"  "Rosiglitazone" "Sulfonylurea"  -1.20  0.1436
"Oyama2008"         "Acarbose"      "Sulfonylurea"  -0.40  0.1549
"Costa1997"         "Acarbose"      "Placebo"       -0.80  0.1432
"Hermansen2007"     "Sitagliptin"   "Placebo"       -0.57  0.1291
"Garber2008"        "Vildagliptin"  "Placebo"       -0.70  0.1273
"Alex1998"          "Metformin"     "Sulfonylurea"  -0.37  0.1184
"Johnston1994"      "Miglitol"      "Placebo"       -0.74  0.1839
"Johnston1998a"     "Miglitol"      "Placebo"       -1.41  0.2235
"Kim2007"           "Rosiglitazone" "Metformin"      0.00  0.2339
"Johnston1998b"     "Miglitol"      "Placebo"       -0.68  0.2828
"GonzalezOrtiz04"   "Metformin"     "Placebo"       -0.40  0.4356
"Stucci1996"        "Benfluorex"    "Placebo"       -0.23  0.3467
"Moulin2006"        "Benfluorex"    "Placebo"       -1.01  0.1366
"Willms1999b"       "Metformin"     "Placebo"       -1.20  0.3758
"Willms1999c"       "Acarbose"      "Placebo"       -1.00  0.4669
end

nma_import te se_te, studyvar(study) treat1(treat1) treat2(treat2) ///
    measure(md) ref(Placebo)
nma_fit, nolog

tempname b_senn
matrix `b_senn' = e(b)
local senn_cnames : colnames `b_senn'
local senn_tau2 = e(tau2)

* Compare each Senn treatment
local senn_treatments "Acarbose Benfluorex Metformin Miglitol Pioglitazone Rosiglitazone Sitagliptin Sulfonylurea Vildagliptin"

foreach t of local senn_treatments {
    local col = 0
    local j = 0
    foreach c of local senn_cnames {
        local ++j
        if "`c'" == "`t'" local col = `j'
    }
    if `col' > 0 {
        local s_s_`t' = abs(`b_senn'[1, `col'])
        local d = abs(`r_s_`t'' - `s_s_`t'')

        local ++test_count
        if `d' < `tol' {
            display as result "  PASS: CV1 — Senn `t' |MD| diff=" %6.4f `d' " (tol=`tol')"
            local ++pass_count
        }
        else if `d' < `tol_note' {
            * NOTE: within 0.10 but outside 0.05 — tau2 sensitivity
            display as result "  PASS: CV1 — Senn `t' |MD| diff=" %6.4f `d' " (NOTE: tau2-sensitive, tol=`tol_note')"
            local ++pass_count
        }
        else {
            display as error "  FAIL: CV1 — Senn `t' |MD| diff=" %6.4f `d' " exceeds `tol_note'"
            display as error "    Stata: " %8.4f `s_s_`t'' "  R: " %8.4f `r_s_`t''
            local ++fail_count
        }
    }
}


* ============================================================
* CV2: Dogliotti 2014 — Anticoagulants in AF (stroke logOR)
* 20 studies, 8 treatments, binary arm-level data
* ============================================================

clear
input str20 study str22 treatment stroke total
"AFASAK_I_1989"      "VKA"          9   335
"AFASAK_I_1989"      "ASA"         16   336
"AFASAK_I_1989"      "Placebo"     19   336
"BAATAF_1990"        "VKA"          3   212
"BAATAF_1990"        "Placebo"     13   208
"CAFA_1991"          "VKA"          6   187
"CAFA_1991"          "Placebo"      9   191
"SPAF_I_1991"        "VKA"          8   210
"SPAF_I_1991"        "ASA"         24   552
"SPAF_I_1991"        "Placebo"     42   568
"SPINAF_1992"        "VKA"          7   260
"SPINAF_1992"        "Placebo"     23   265
"EAFT_1993"          "VKA"         20   225
"EAFT_1993"          "ASA"         88   404
"EAFT_1993"          "Placebo"     90   378
"SPAF_II_1994"       "VKA"         39   555
"SPAF_II_1994"       "ASA"         42   545
"AFASAK_II_1998"     "VKA"         10   170
"AFASAK_II_1998"     "ASA"          9   169
"PATAF_1999"         "VKA"          3   131
"PATAF_1999"         "ASA"         22   319
"LASAF_1999"         "ASA"          5   194
"LASAF_1999"         "Placebo"      3    91
"ACTIVE_W_2006"      "VKA"         59  3371
"ACTIVE_W_2006"      "ASA_Clop"   100  3335
"JAST_2006"          "ASA"         17   426
"JAST_2006"          "Placebo"     18   445
"ACTIVE_A_2006"      "ASA_Clop"   296  3772
"ACTIVE_A_2006"      "ASA"        408  3782
"Chinese_ATAFS_2006" "VKA"          9   335
"Chinese_ATAFS_2006" "ASA"         17   369
"BAFTA_2007"         "VKA"         21   488
"BAFTA_2007"         "ASA"         44   485
"WASPO_2007"         "VKA"          0    36
"WASPO_2007"         "ASA"          0    39
"RE_LY_2009"         "Dab110"     171  6015
"RE_LY_2009"         "Dab150"     122  6076
"RE_LY_2009"         "VKA"        185  6022
"ROCKET_2011"        "Rivarox"    188  7081
"ROCKET_2011"        "VKA"        240  7090
"ARISTOTLE_2011"     "Apixaban"   197  9120
"ARISTOTLE_2011"     "VKA"        248  9081
"AVERROES_2011"      "Apixaban"    49  2808
"AVERROES_2011"      "ASA"        105  2791
end

nma_setup stroke total, studyvar(study) trtvar(treatment) ref(Placebo)
nma_fit, nolog

tempname b_dog
matrix `b_dog' = e(b)
local dog_cnames : colnames `b_dog'
local dog_tau2 = e(tau2)

* Compare each Dogliotti treatment
local dog_treatments "Apixaban ASA ASA_Clop Dab110 Dab150 Rivarox VKA"

foreach t of local dog_treatments {
    local col = 0
    local j = 0
    foreach c of local dog_cnames {
        local ++j
        if "`c'" == "`t'" local col = `j'
    }
    if `col' > 0 {
        local s_d_`t' = abs(`b_dog'[1, `col'])
        local d = abs(`r_d_`t'' - `s_d_`t'')

        local ++test_count
        if `d' < `tol' {
            display as result "  PASS: CV2 — Dogliotti `t' |logOR| diff=" %6.4f `d' " (tol=`tol')"
            local ++pass_count
        }
        else {
            display as error "  FAIL: CV2 — Dogliotti `t' |logOR| diff=" %6.4f `d' " exceeds `tol'"
            display as error "    Stata: " %8.4f `s_d_`t'' "  R: " %8.4f `r_d_`t''
            local ++fail_count
        }
    }
}


* ============================================================
* Build results dataset and export to xlsx
* ============================================================

clear
local total_rows = 9 + 7 + 2
set obs `total_rows'

gen str20 dataset = ""
gen str20 treatment = ""
gen double r_value = .
gen double stata_value = .
gen double diff = .
gen str6 status = ""

local row = 0

foreach t of local senn_treatments {
    local ++row
    quietly replace dataset = "Senn 2013" in `row'
    quietly replace treatment = "`t'" in `row'
    quietly replace r_value = `r_s_`t'' in `row'
    quietly replace stata_value = `s_s_`t'' in `row'
    local d = abs(`r_s_`t'' - `s_s_`t'')
    quietly replace diff = `d' in `row'
    if `d' < `tol' {
        quietly replace status = "PASS" in `row'
    }
    else if `d' < `tol_note' {
        quietly replace status = "NOTE*" in `row'
    }
    else {
        quietly replace status = "FAIL" in `row'
    }
}

local ++row
quietly replace dataset = "Senn 2013" in `row'
quietly replace treatment = "tau2" in `row'
quietly replace r_value = `r_s_tau2' in `row'
quietly replace stata_value = `senn_tau2' in `row'
quietly replace diff = abs(`r_s_tau2' - `senn_tau2') in `row'
quietly replace status = "INFO" in `row'

foreach t of local dog_treatments {
    local ++row
    quietly replace dataset = "Dogliotti 2014" in `row'
    quietly replace treatment = "`t'" in `row'
    quietly replace r_value = `r_d_`t'' in `row'
    quietly replace stata_value = `s_d_`t'' in `row'
    local d = abs(`r_d_`t'' - `s_d_`t'')
    quietly replace diff = `d' in `row'
    if `d' < `tol' {
        quietly replace status = "PASS" in `row'
    }
    else {
        quietly replace status = "FAIL" in `row'
    }
}

local ++row
quietly replace dataset = "Dogliotti 2014" in `row'
quietly replace treatment = "tau2" in `row'
quietly replace r_value = `r_d_tau2' in `row'
quietly replace stata_value = `dog_tau2' in `row'
quietly replace diff = abs(`r_d_tau2' - `dog_tau2') in `row'
quietly replace status = "INFO" in `row'

* Display comparison table
display as text %16s "Dataset" "  " %16s "Treatment" "  " %10s "R netmeta" "  " %10s "Stata nma" "  " %8s "Diff" "  " %6s "Status"

forvalues i = 1/`=_N' {
    display as text %16s dataset[`i'] "  " %16s treatment[`i'] ///
        "  " %10.4f r_value[`i'] "  " %10.4f stata_value[`i'] ///
        "  " %8.4f diff[`i'] "  " %6s status[`i']
}

capture erase "`outfile'"
quietly {
    putexcel set "`outfile'", sheet("Cross-Validation") replace

    putexcel A1 = "Cross-Validation: Stata nma vs R netmeta 3.3-1"
    putexcel A2 = "Published datasets: Senn 2013 (10 treatments) + Dogliotti 2014 (8 treatments)"
    putexcel A3 = "Date: `c(current_date)'"

    putexcel A5 = "Dataset" B5 = "Treatment" C5 = "R netmeta" ///
        D5 = "Stata nma" E5 = "Diff" F5 = "Status"

    forvalues i = 1/`=_N' {
        local r = `i' + 5
        putexcel A`r' = dataset[`i']
        putexcel B`r' = treatment[`i']
        putexcel C`r' = r_value[`i'], nformat(#0.0000)
        putexcel D`r' = stata_value[`i'], nformat(#0.0000)
        putexcel E`r' = diff[`i'], nformat(#0.0000)
        putexcel F`r' = status[`i']
    }

    local sr = _N + 7
    putexcel A`sr' = "Summary"
    putexcel B`sr' = "PASS: `pass_count'  FAIL: `fail_count'"

    local nr = `sr' + 2
    putexcel A`nr' = "Notes:"
    local ++nr
    putexcel A`nr' = "  - Coefficients compared as absolute values (sign convention differs)"
    local ++nr
    putexcel A`nr' = "  - R netmeta: graph-theoretical REML (Rucker 2012)"
    local ++nr
    putexcel A`nr' = "  - Stata nma: multivariate REML"
    local ++nr
    putexcel A`nr' = "  - tau2 differences explain NOTE* on Benfluorex (2 studies, tau2-sensitive)"
    local ++nr
    putexcel A`nr' = "  - Tolerance: 0.05 for PASS, 0.10 for NOTE*, >0.10 = FAIL"
    local ++nr
    putexcel A`nr' = "  - INFO rows (tau2) are not graded pass/fail"

    putexcel save
}

display as text "Results exported to `outfile'"


* ============================================================
* Summary
* ============================================================

display as result "Cross-Validation: `pass_count'/`test_count' passed, `fail_count' failed"

if `fail_count' > 0 {
    display as error "CROSS-VALIDATION FAILURES"
    exit 1
}
else {
    display as result "ALL CROSS-VALIDATIONS PASSED"
}
