#!/usr/bin/env python3
"""Build deterministic CCI vectors from the pinned Ludvigsson Stata source.

The source is parsed rather than translated by hand.  Each published regex
prefix becomes a positive membership case.  Normalization variants and every
hole in the package's generated malignancy ranges are emitted as separate
cases, so mapping membership cannot be masked by separator normalization.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
from collections import defaultdict
from pathlib import Path


SOURCE_URL = (
    "https://raw.githubusercontent.com/bjoroeKI/"
    "Charlson-comorbidity-index-revisited/"
    "0f2b6058fa551deb6d4b68116a21551f13ef99bc/Charlson_STATA"
)
SOURCE_SHA256 = "ed865ef10f2d0f29235091ec6ec1e921b2db39b17cf9e37624f2b75f84868acd"

ERA_YEAR = {7: 1968, 8: 1986, 9: 1996, 10: 1998}
PUBLIC_COMPONENTS = {
    1: "mi",
    2: "chf",
    3: "pvd",
    4: "cevd",
    5: "copd",
    6: "pulm",
    7: "rheum",
    8: "dem",
    9: "plegia",
    10: "diab",
    11: "diabcomp",
    12: "renal",
    13: "livmild",
    15: "livsev",
    16: "pud",
    17: "cancer",
    18: "mets",
    19: "aids",
}
WEIGHTS = defaultdict(lambda: 1, {9: 2, 11: 2, 12: 2, 15: 3, 17: 2, 18: 6, 19: 6})


def normalized(code: str) -> str:
    return code.upper().replace(",", "").replace(".", "").strip()


def parse_source(source: str) -> dict[int, dict[str, set[int]]]:
    """Return era -> normalized prefix -> raw ch component set."""
    pending: dict[int, list[str]] = {}
    mapping: dict[int, dict[str, set[int]]] = {
        era: defaultdict(set) for era in ERA_YEAR
    }
    regex_line = re.compile(r'^gen ICD(7|8|9|10) = regexm\(diagnos, "([^"]*)"\)')
    component_line = re.compile(r"^gen ch(\d+) =")

    for raw_line in source.splitlines():
        line = raw_line.strip()
        match = regex_line.match(line)
        if match:
            era = int(match.group(1))
            tokens = [token.strip() for token in match.group(2).split("|")]
            pending[era] = [token for token in tokens if token]
            continue

        match = component_line.match(line)
        if not match:
            continue
        component = int(match.group(1))
        for era, tokens in pending.items():
            for token in tokens:
                mapping[era][normalized(token)].add(component)
        pending = {}

    if pending:
        raise ValueError("unassigned ICD regex block at end of source")
    if not all(mapping[era] for era in ERA_YEAR):
        raise ValueError("source parser did not recover every ICD era")
    return mapping


def classify(code: str, era_mapping: dict[str, set[int]]) -> dict[int, int]:
    value = normalized(code)
    flags = {index: 0 for index in range(1, 20)}
    for prefix, components in era_mapping.items():
        if value.startswith(prefix):
            for component in components:
                flags[component] = 1

    if flags[13] and flags[14]:
        flags[15] = 1
    if flags[15]:
        flags[13] = 0
    if flags[11]:
        flags[10] = 0
    if flags[18]:
        flags[17] = 0
    return flags


def make_row(
    case_id: int,
    era: int,
    code: str,
    kind: str,
    mapping: dict[int, dict[str, set[int]]],
) -> dict[str, object]:
    flags = classify(code, mapping[era])
    row: dict[str, object] = {
        "case_id": case_id,
        "era": era,
        "year": ERA_YEAR[era],
        "code": code,
        "case_kind": kind,
        "expected_score": sum(flags[index] * WEIGHTS[index] for index in range(1, 20) if index != 14),
    }
    for index, name in PUBLIC_COMPONENTS.items():
        row[f"expected_{name}"] = flags[index]
    return row


def build_rows(mapping: dict[int, dict[str, set[int]]]) -> list[dict[str, object]]:
    cases: list[tuple[int, str, str]] = []

    # One canonical membership case for every unique authoritative prefix.
    for era in ERA_YEAR:
        for prefix in sorted(mapping[era]):
            cases.append((era, prefix, "authoritative_prefix"))

    # Separator and case normalization are distinct from membership coverage.
    seen_variants: set[tuple[int, str]] = set()
    for era in ERA_YEAR:
        for prefix in sorted(mapping[era]):
            variants = {prefix.lower()}
            if len(prefix) > 3:
                variants.add(prefix[:3] + "." + prefix[3:])
                variants.add(prefix[:3] + "," + prefix[3:])
            for variant in sorted(variants):
                key = (era, variant)
                if normalized(variant) == prefix and key not in seen_variants:
                    seen_variants.add(key)
                    cases.append((era, variant, "normalization_variant"))

    # Every malignancy hole within a range generated by cci_se.ado.
    generated_ranges = {
        7: [f"{value:03d}" for value in list(range(140, 198)) + list(range(200, 205))],
        8: [f"{value:03d}" for value in range(140, 210)],
        9: [f"{value:03d}" for value in range(140, 209)],
        10: [f"C{value:02d}" for value in list(range(0, 77)) + list(range(81, 98))],
    }
    for era, generated in generated_ranges.items():
        for code in generated:
            flags = classify(code, mapping[era])
            if not flags[17]:
                cases.append((era, code, "malignancy_generated_range_hole"))

    for era, code in ((7, "139"), (7, "205"), (8, "139"), (8, "210"),
                      (9, "139"), (9, "209"), (10, "C98"), (10, "C99")):
        cases.append((era, code, "malignancy_range_boundary"))

    # Preserve distinct kinds but remove accidental duplicates within a kind.
    unique: list[tuple[int, str, str]] = []
    seen: set[tuple[int, str, str]] = set()
    for case in cases:
        if case not in seen:
            seen.add(case)
            unique.append(case)
    return [make_row(i, era, code, kind, mapping) for i, (era, code, kind) in enumerate(unique, 1)]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source_bytes = args.source.read_bytes()
    digest = hashlib.sha256(source_bytes).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(
            f"source SHA-256 mismatch: expected {SOURCE_SHA256}, observed {digest}"
        )

    mapping = parse_source(source_bytes.decode("utf-8"))
    rows = build_rows(mapping)
    fieldnames = list(rows[0])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    output_digest = hashlib.sha256(args.output.read_bytes()).hexdigest()
    print(f"source_url={SOURCE_URL}")
    print(f"source_sha256={SOURCE_SHA256}")
    print(f"rows={len(rows)}")
    print(f"fixture_sha256={output_digest}")


if __name__ == "__main__":
    main()
