* crossval_external_replication.do - external Python replication for gcomp
* Manual run from this qa/ directory: stata-mp -b do crossval_external_replication.do
* Fixtures: qa/data/external_*.csv generated by qa/data/generate_external_replication.py

clear all
version 16.0

local test_count = 0
local pass_count = 0
local fail_count = 0
local failed_tests ""

local qa_dir "`c(pwd)'"
local pkg_dir = subinstr("`qa_dir'", "/qa", "", 1)

capture ado uninstall gcomp
quietly net install gcomp, from("`pkg_dir'") replace
discard

preserve
import delimited using "`qa_dir'/data/external_reference.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local analysis = analysis[`i']
    local metric = metric[`i']
    if "`analysis'" == "mediation_binary" local key "mb"
    else if "`analysis'" == "mediation_continuous" local key "mc"
    else if "`analysis'" == "timevarying_binary" local key "tvb"
    else if "`analysis'" == "timevarying_continuous" local key "tvc"
    local ref_`key'_`metric' = value[`i']
    local tol_`key'_`metric' = tolerance[`i']
}
restore

capture program drop _external_compare
program define _external_compare
    version 16.0
    syntax, ACTual(real) EXpected(real) TOLerance(real) LABEL(string)

    local diff = abs(`actual' - `expected')
    noisily display as text "    `label': Stata=" %12.9f `actual' ///
        " Python=" %12.9f `expected' " diff=" %10.8f `diff' ///
        " tol=" %10.8f `tolerance'
    assert `diff' <= `tolerance'
end

**# Mediation: binary mediator and binary outcome
local ++test_count
capture noisily {
    import delimited using "`qa_dir'/data/external_mediation_binary.csv", clear asdouble

    gcomp y m x c, outcome(y) mediation obe ///
        exposure(x) mediator(m) base_confs(c) control(0) ///
        commands(m: logit, y: logit) ///
        equations(m: x c, y: m x c) ///
        sim(5000) samples(5) seed(20260506) minsim moreMC

    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "mediation"
    assert "`e(mediation_type)'" == "obe"
    assert "`e(scale)'" == "RD"

    local gc_tce = e(tce)
    local gc_nde = e(nde)
    local gc_nie = e(nie)
    local gc_pm = e(pm)
    local gc_cde = e(cde)

    _external_compare, actual(`gc_tce') expected(`ref_mb_tce') ///
        tolerance(`tol_mb_tce') label("binary mediation TCE")
    _external_compare, actual(`gc_nde') expected(`ref_mb_nde') ///
        tolerance(`tol_mb_nde') label("binary mediation NDE")
    _external_compare, actual(`gc_nie') expected(`ref_mb_nie') ///
        tolerance(`tol_mb_nie') label("binary mediation NIE")
    _external_compare, actual(`gc_pm') expected(`ref_mb_pm') ///
        tolerance(`tol_mb_pm') label("binary mediation PM")
    _external_compare, actual(`gc_cde') expected(`ref_mb_cde') ///
        tolerance(`tol_mb_cde') label("binary mediation CDE")
}
if _rc == 0 {
    display as result "  PASS: external binary-outcome mediation replication"
    local ++pass_count
}
else {
    display as error "  FAIL: external binary-outcome mediation replication (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' mediation_binary"
}

**# Mediation: binary mediator and continuous outcome
local ++test_count
capture noisily {
    import delimited using "`qa_dir'/data/external_mediation_continuous.csv", clear asdouble

    gcomp y m x c, outcome(y) mediation obe ///
        exposure(x) mediator(m) base_confs(c) control(0) ///
        commands(m: logit, y: regress) ///
        equations(m: x c, y: m x c) ///
        sim(5000) samples(5) seed(20260507) minsim moreMC

    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "mediation"
    assert "`e(mediation_type)'" == "obe"
    assert "`e(scale)'" == "RD"

    local gc_tce = e(tce)
    local gc_nde = e(nde)
    local gc_nie = e(nie)
    local gc_pm = e(pm)
    local gc_cde = e(cde)

    _external_compare, actual(`gc_tce') expected(`ref_mc_tce') ///
        tolerance(`tol_mc_tce') label("continuous mediation TCE")
    _external_compare, actual(`gc_nde') expected(`ref_mc_nde') ///
        tolerance(`tol_mc_nde') label("continuous mediation NDE")
    _external_compare, actual(`gc_nie') expected(`ref_mc_nie') ///
        tolerance(`tol_mc_nie') label("continuous mediation NIE")
    _external_compare, actual(`gc_pm') expected(`ref_mc_pm') ///
        tolerance(`tol_mc_pm') label("continuous mediation PM")
    _external_compare, actual(`gc_cde') expected(`ref_mc_cde') ///
        tolerance(`tol_mc_cde') label("continuous mediation CDE")
}
if _rc == 0 {
    display as result "  PASS: external continuous-outcome mediation replication"
    local ++pass_count
}
else {
    display as error "  FAIL: external continuous-outcome mediation replication (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' mediation_continuous"
}

**# Time-varying g-computation: binary end-of-follow-up outcome
local ++test_count
capture noisily {
    import delimited using "`qa_dir'/data/external_timevarying.csv", clear asdouble

    gcomp y l0 a l alag llag id time, outcome(y) ///
        idvar(id) tvar(time) ///
        varyingcovariates(l) fixedcovariates(l0) ///
        laggedvars(alag llag) ///
        lagrules(alag: a 1, llag: l 1) ///
        intvars(a) interventions(a=1, a=0) eofu ///
        commands(a: logit, y: logit, l: regress) ///
        equations(a: l0 l, y: alag llag l0, l: alag llag l0) ///
        sim(450) samples(5) seed(20260508) minsim

    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "time_varying"

    tempname b
    matrix `b' = e(b)
    local po_a1 = `b'[1, colnumb(`b', "PO1")]
    local po_a0 = `b'[1, colnumb(`b', "PO2")]
    local rd = `po_a1' - `po_a0'

    _external_compare, actual(`po_a1') expected(`ref_tvb_po_a1') ///
        tolerance(`tol_tvb_po_a1') label("time-varying binary PO A=1")
    _external_compare, actual(`po_a0') expected(`ref_tvb_po_a0') ///
        tolerance(`tol_tvb_po_a0') label("time-varying binary PO A=0")
    _external_compare, actual(`rd') expected(`ref_tvb_rd_a1_a0') ///
        tolerance(`tol_tvb_rd_a1_a0') label("time-varying binary RD")
}
if _rc == 0 {
    display as result "  PASS: external binary-outcome time-varying replication"
    local ++pass_count
}
else {
    display as error "  FAIL: external binary-outcome time-varying replication (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' timevarying_binary"
}

**# Time-varying g-computation: continuous end-of-follow-up outcome
local ++test_count
capture noisily {
    import delimited using "`qa_dir'/data/external_timevarying.csv", clear asdouble

    gcomp yc l0 a l alag llag id time, outcome(yc) ///
        idvar(id) tvar(time) ///
        varyingcovariates(l) fixedcovariates(l0) ///
        laggedvars(alag llag) ///
        lagrules(alag: a 1, llag: l 1) ///
        intvars(a) interventions(a=1, a=0) eofu ///
        commands(a: logit, yc: regress, l: regress) ///
        equations(a: l0 l, yc: alag llag l0, l: alag llag l0) ///
        sim(450) samples(5) seed(20260508) minsim

    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "time_varying"

    tempname b
    matrix `b' = e(b)
    local po_a1 = `b'[1, colnumb(`b', "PO1")]
    local po_a0 = `b'[1, colnumb(`b', "PO2")]
    local rd = `po_a1' - `po_a0'

    _external_compare, actual(`po_a1') expected(`ref_tvc_po_a1') ///
        tolerance(`tol_tvc_po_a1') label("time-varying continuous PO A=1")
    _external_compare, actual(`po_a0') expected(`ref_tvc_po_a0') ///
        tolerance(`tol_tvc_po_a0') label("time-varying continuous PO A=0")
    _external_compare, actual(`rd') expected(`ref_tvc_rd_a1_a0') ///
        tolerance(`tol_tvc_rd_a1_a0') label("time-varying continuous RD")
}
if _rc == 0 {
    display as result "  PASS: external continuous-outcome time-varying replication"
    local ++pass_count
}
else {
    display as error "  FAIL: external continuous-outcome time-varying replication (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' timevarying_continuous"
}

capture program drop _external_compare

display as text ""
display as result "External replication results: `pass_count'/`test_count' passed, `fail_count' failed"
if `fail_count' > 0 {
    display "RESULT: crossval_external_replication tests=`test_count' pass=`pass_count' fail=`fail_count' status=FAIL"
    display as error "FAIL"
    display as error "Failed scenarios:`failed_tests'"
    exit 1
}
display "RESULT: crossval_external_replication tests=`test_count' pass=`pass_count' fail=`fail_count' status=PASS"
display as result "PASS"
