* crossval_mediation_extended.do - Extended mediation external-oracle QA
* Manual run from this qa/ directory: stata-mp -b do crossval_mediation_extended.do
* Fixtures: data/mediation_extended_*.csv generated by data/generate_mediation_extended_reference.py

clear all
version 16.0
set varabbrev off

local qa_dir "`c(pwd)'"
local pkg_dir = subinstr("`qa_dir'", "/qa", "", 1)

capture noisily shell python3 "`qa_dir'/data/generate_mediation_extended_reference.py"
if _rc {
    display as error "Python statsmodels extended mediation reference generation failed"
    display "RESULT: crossval_mediation_extended tests=0 pass=0 fail=1 status=FAIL"
    exit 1
}

foreach fixture in reference covariance categorical linexp {
    capture confirm file "`qa_dir'/data/mediation_extended_`fixture'.csv"
    if _rc {
        display as error "Missing data/mediation_extended_`fixture'.csv"
        display "RESULT: crossval_mediation_extended tests=1 pass=0 fail=1 status=FAIL"
        exit 1
    }
}

capture ado uninstall gcomp
quietly net install gcomp, from("`pkg_dir'") replace
discard

preserve
import delimited using "`qa_dir'/data/mediation_extended_reference.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local scenario = scenario[`i']
    local effect = stata_effect[`i']
    if "`scenario'" == "oce_mlogit_logit" local key "oce"
    else if "`scenario'" == "specific_mlogit_logit" local key "sp"
    else if "`scenario'" == "linexp_linear_linear" local key "lin"
    local ref_`key'_`effect'_p = point[`i']
    local ref_`key'_`effect'_s = se[`i']
    local ptol_`key'_`effect' = point_abs_tol[`i']
    local satol_`key'_`effect' = se_abs_tol[`i']
    local srtol_`key'_`effect' = se_rel_tol[`i']
}
restore

preserve
import delimited using "`qa_dir'/data/mediation_extended_covariance.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local scenario = scenario[`i']
    local effect1 = stata_effect1[`i']
    local effect2 = stata_effect2[`i']
    if "`scenario'" == "oce_mlogit_logit" local key "oce"
    else if "`scenario'" == "specific_mlogit_logit" local key "sp"
    else if "`scenario'" == "linexp_linear_linear" local key "lin"
    local cov_`key'_`effect1'_`effect2' = covariance[`i']
    local covtol_`key'_`effect1'_`effect2' = cov_abs_tol[`i']
}
restore

tempname pf
tempfile checks
postfile `pf' str8 op str180 label double actual expected tolerance using `checks', replace

**# OCE categorical exposure with multinomial mediator
capture noisily {
    import delimited using "`qa_dir'/data/mediation_extended_categorical.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation oce ///
        exposure(x) mediator(m) base_confs(c1 c2) baseline(0) control(0) ///
        commands(m: mlogit, y: logit) ///
        equations(m: i.x c1 c2, y: i.m i.x c1 c2) ///
        sim(9000) samples(100) seed(202605071) minsim moreMC
}
local rc = _rc
post `pf' ("eq") ("OCE mlogit/logit RD: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    post `pf' ("eq") ("OCE mlogit/logit RD: e(mediation_type)") (`"`e(mediation_type)'"' == "oce") (1) (0)
    post `pf' ("eq") ("OCE mlogit/logit RD: e(scale)") (`"`e(scale)'"' == "RD") (1) (0)
    tempname B S V
    matrix `B' = e(b)
    matrix `S' = e(se)
    matrix `V' = e(V)
    local key "oce"
    foreach effect in tce_1 nde_1 nie_1 pm_1 cde_1 tce_2 nde_2 nie_2 pm_2 cde_2 {
        local bcol = colnumb(`B', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `bcol' >= . | `scol' >= . {
            post `pf' ("eq") ("OCE mlogit/logit RD: `effect' column exists") (0) (1) (0)
        }
        else {
            local point_actual = `B'[1, `bcol']
            local se_actual = `S'[1, `scol']
            local point_expected = `ref_`key'_`effect'_p'
            local se_expected = `ref_`key'_`effect'_s'
            local point_tol = `ptol_`key'_`effect''
            local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
            post `pf' ("abs") ("OCE mlogit/logit RD: `effect' point") (`point_actual') (`point_expected') (`point_tol')
            post `pf' ("abs") ("OCE mlogit/logit RD: `effect' SE") (`se_actual') (`se_expected') (`se_tol')
            local from_v = sqrt(`V'[`bcol', `bcol'])
            local diag_tol = max(1e-8, abs(`se_actual') * 1e-6)
            post `pf' ("abs") ("OCE mlogit/logit RD: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`se_actual') (`diag_tol')
        }
    }
    local maxoff = 0
    foreach pair in "tce_1 nde_1" "tce_1 cde_1" "nde_1 cde_1" "nde_1 pm_1" "pm_1 cde_1" ///
        "tce_2 nde_2" "tce_2 cde_2" "nde_2 cde_2" "nde_2 pm_2" "pm_2 cde_2" {
        gettoken e1 e2 : pair
        local e1 = strtrim("`e1'")
        local e2 = strtrim("`e2'")
        capture local vpos1 = colnumb(`V', "`e1'")
        if _rc | "`vpos1'" == "" local vpos1 .
        capture local vpos2 = colnumb(`V', "`e2'")
        if _rc | "`vpos2'" == "" local vpos2 .
        if `vpos1' < . & `vpos2' < . {
            local off = abs(`V'[`vpos1', `vpos2'])
            if `off' > `maxoff' local maxoff = `off'
            local cov_actual = `V'[`vpos1', `vpos2']
            local cov_expected = `cov_`key'_`e1'_`e2''
            local cov_tol = `covtol_`key'_`e1'_`e2''
            post `pf' ("abs") ("OCE mlogit/logit RD: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
        }
        else {
            post `pf' ("eq") ("OCE mlogit/logit RD: covariance columns `e1'-`e2' exist") (0) (1) (0)
        }
    }
    post `pf' ("gtabs") ("OCE mlogit/logit RD: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
}

**# Specific categorical comparison with multinomial mediator
capture noisily {
    import delimited using "`qa_dir'/data/mediation_extended_categorical.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation specific ///
        exposure(x) mediator(m) base_confs(c1 c2) baseline(0) alternative(2) control(0) ///
        commands(m: mlogit, y: logit) ///
        equations(m: i.x c1 c2, y: i.m i.x c1 c2) ///
        sim(9000) samples(100) seed(202605072) minsim moreMC
}
local rc = _rc
post `pf' ("eq") ("specific mlogit/logit RD: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    post `pf' ("eq") ("specific mlogit/logit RD: e(mediation_type)") (`"`e(mediation_type)'"' == "specific") (1) (0)
    post `pf' ("eq") ("specific mlogit/logit RD: e(scale)") (`"`e(scale)'"' == "RD") (1) (0)
    tempname B S V
    matrix `B' = e(b)
    matrix `S' = e(se)
    matrix `V' = e(V)
    local key "sp"
    foreach effect in tce nde nie pm cde {
        local bcol = colnumb(`B', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `bcol' >= . | `scol' >= . {
            post `pf' ("eq") ("specific mlogit/logit RD: `effect' column exists") (0) (1) (0)
        }
        else {
            local point_actual = `B'[1, `bcol']
            local se_actual = `S'[1, `scol']
            local point_expected = `ref_`key'_`effect'_p'
            local se_expected = `ref_`key'_`effect'_s'
            local point_tol = `ptol_`key'_`effect''
            local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
            post `pf' ("abs") ("specific mlogit/logit RD: `effect' point") (`point_actual') (`point_expected') (`point_tol')
            post `pf' ("abs") ("specific mlogit/logit RD: `effect' SE") (`se_actual') (`se_expected') (`se_tol')
            local from_v = sqrt(`V'[`bcol', `bcol'])
            local diag_tol = max(1e-8, abs(`se_actual') * 1e-6)
            post `pf' ("abs") ("specific mlogit/logit RD: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`se_actual') (`diag_tol')
        }
    }
    local maxoff = 0
    foreach pair in "tce nde" "tce cde" "nde cde" "nde pm" "pm cde" {
        gettoken e1 e2 : pair
        local e1 = strtrim("`e1'")
        local e2 = strtrim("`e2'")
        capture local vpos1 = colnumb(`V', "`e1'")
        if _rc | "`vpos1'" == "" local vpos1 .
        capture local vpos2 = colnumb(`V', "`e2'")
        if _rc | "`vpos2'" == "" local vpos2 .
        if `vpos1' < . & `vpos2' < . {
            local off = abs(`V'[`vpos1', `vpos2'])
            if `off' > `maxoff' local maxoff = `off'
            local cov_actual = `V'[`vpos1', `vpos2']
            local cov_expected = `cov_`key'_`e1'_`e2''
            local cov_tol = `covtol_`key'_`e1'_`e2''
            post `pf' ("abs") ("specific mlogit/logit RD: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
        }
        else {
            post `pf' ("eq") ("specific mlogit/logit RD: covariance columns `e1'-`e2' exist") (0) (1) (0)
        }
    }
    post `pf' ("gtabs") ("specific mlogit/logit RD: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
}

**# Linexp continuous exposure with linear mediator/outcome
capture noisily {
    import delimited using "`qa_dir'/data/mediation_extended_linexp.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation linexp ///
        exposure(x) mediator(m) base_confs(c1 c2) control(0) ///
        commands(m: regress, y: regress) ///
        equations(m: x c1 c2, y: m x c1 c2) ///
        sim(9000) samples(100) seed(202605073) minsim moreMC
}
local rc = _rc
post `pf' ("eq") ("linexp linear/linear RD: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    post `pf' ("eq") ("linexp linear/linear RD: e(mediation_type)") (`"`e(mediation_type)'"' == "linexp") (1) (0)
    post `pf' ("eq") ("linexp linear/linear RD: e(scale)") (`"`e(scale)'"' == "RD") (1) (0)
    tempname B S V
    matrix `B' = e(b)
    matrix `S' = e(se)
    matrix `V' = e(V)
    local key "lin"
    foreach effect in tce nde nie pm cde {
        local bcol = colnumb(`B', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `bcol' >= . | `scol' >= . {
            post `pf' ("eq") ("linexp linear/linear RD: `effect' column exists") (0) (1) (0)
        }
        else {
            local point_actual = `B'[1, `bcol']
            local se_actual = `S'[1, `scol']
            local point_expected = `ref_`key'_`effect'_p'
            local se_expected = `ref_`key'_`effect'_s'
            local point_tol = `ptol_`key'_`effect''
            local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
            post `pf' ("abs") ("linexp linear/linear RD: `effect' point") (`point_actual') (`point_expected') (`point_tol')
            post `pf' ("abs") ("linexp linear/linear RD: `effect' SE") (`se_actual') (`se_expected') (`se_tol')
            local from_v = sqrt(`V'[`bcol', `bcol'])
            local diag_tol = max(1e-8, abs(`se_actual') * 1e-6)
            post `pf' ("abs") ("linexp linear/linear RD: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`se_actual') (`diag_tol')
        }
    }
    local maxoff = 0
    foreach pair in "tce nde" "tce cde" "nde cde" "nde pm" "pm cde" {
        gettoken e1 e2 : pair
        local e1 = strtrim("`e1'")
        local e2 = strtrim("`e2'")
        capture local vpos1 = colnumb(`V', "`e1'")
        if _rc | "`vpos1'" == "" local vpos1 .
        capture local vpos2 = colnumb(`V', "`e2'")
        if _rc | "`vpos2'" == "" local vpos2 .
        if `vpos1' < . & `vpos2' < . {
            local off = abs(`V'[`vpos1', `vpos2'])
            if `off' > `maxoff' local maxoff = `off'
            local cov_actual = `V'[`vpos1', `vpos2']
            local cov_expected = `cov_`key'_`e1'_`e2''
            local cov_tol = `covtol_`key'_`e1'_`e2''
            post `pf' ("abs") ("linexp linear/linear RD: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
        }
        else {
            post `pf' ("eq") ("linexp linear/linear RD: covariance columns `e1'-`e2' exist") (0) (1) (0)
        }
    }
    post `pf' ("gtabs") ("linexp linear/linear RD: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
}

postclose `pf'

use `checks', clear
gen double diff = abs(actual - expected)
gen byte passed = .
replace passed = (diff <= tolerance) if op == "abs"
replace passed = (actual == expected) if op == "eq"
replace passed = (abs(actual) > tolerance) if op == "gtabs"

local test_count = _N
quietly count if passed == 1
local pass_count = r(N)
quietly count if passed != 1
local fail_count = r(N)

forvalues i = 1/`=_N' {
    if passed[`i'] == 1 {
        if op[`i'] == "gtabs" {
            display as result "  PASS: " label[`i'] " offdiag=" %10.8f actual[`i'] " min=" %10.8f tolerance[`i']
        }
        else {
            display as result "  PASS: " label[`i'] " actual=" %12.8f actual[`i'] ///
                " expected=" %12.8f expected[`i'] " diff=" %10.8f diff[`i'] ///
                " tol=" %10.8f tolerance[`i']
        }
    }
    else {
        if op[`i'] == "gtabs" {
            display as error "  FAIL: " label[`i'] " offdiag=" %10.8f actual[`i'] " min=" %10.8f tolerance[`i']
        }
        else {
            display as error "  FAIL: " label[`i'] " actual=" %12.8f actual[`i'] ///
                " expected=" %12.8f expected[`i'] " diff=" %10.8f diff[`i'] ///
                " tol=" %10.8f tolerance[`i']
        }
    }
}

display as text ""
display as result "Extended mediation cross-validation results: `pass_count'/`test_count' passed, `fail_count' failed"
if `fail_count' > 0 {
    display "RESULT: crossval_mediation_extended tests=`test_count' pass=`pass_count' fail=`fail_count' status=FAIL"
    exit 1
}
display "RESULT: crossval_mediation_extended tests=`test_count' pass=`pass_count' fail=`fail_count' status=PASS"
