* crossval_mediation_se.do - Python statsmodels mediation SE cross-validation
* Manual run from this qa/ directory: stata-mp -b do crossval_mediation_se.do
* Fixtures: data/mediation_se_*.csv generated by data/generate_mediation_se_reference.py

clear all
version 16.0
set more off
set varabbrev off

local qa_dir "`c(pwd)'"
local pkg_dir = subinstr("`qa_dir'", "/qa", "", 1)

capture noisily shell python3 "`qa_dir'/data/generate_mediation_se_reference.py"
if _rc {
    display as error "Python statsmodels mediation reference generation failed"
    display "RESULT: crossval_mediation_se tests=0 pass=0 fail=1 status=FAIL"
    exit 1
}

capture confirm file "`qa_dir'/data/mediation_se_reference.csv"
if _rc {
    display as error "Missing data/mediation_se_reference.csv"
    display "RESULT: crossval_mediation_se tests=1 pass=0 fail=1 status=FAIL"
    exit 1
}
capture confirm file "`qa_dir'/data/mediation_se_covariance.csv"
if _rc {
    display as error "Missing data/mediation_se_covariance.csv"
    display "RESULT: crossval_mediation_se tests=1 pass=0 fail=1 status=FAIL"
    exit 1
}
capture confirm file "`qa_dir'/data/mediation_se_binary.csv"
if _rc {
    display as error "Missing data/mediation_se_binary.csv"
    display "RESULT: crossval_mediation_se tests=1 pass=0 fail=1 status=FAIL"
    exit 1
}
capture confirm file "`qa_dir'/data/mediation_se_continuous.csv"
if _rc {
    display as error "Missing data/mediation_se_continuous.csv"
    display "RESULT: crossval_mediation_se tests=1 pass=0 fail=1 status=FAIL"
    exit 1
}

capture ado uninstall gcomp
quietly net install gcomp, from("`pkg_dir'") replace
discard

preserve
import delimited using "`qa_dir'/data/mediation_se_reference.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local scenario = scenario[`i']
    local scale = scale[`i']
    local effect = effect[`i']
    if "`scenario'" == "binary_logit_logit" {
        local skey "b"
    }
    else {
        local skey "c"
    }
    local ref_`skey'_`scale'_`effect'_p = point[`i']
    local ref_`skey'_`scale'_`effect'_s = se[`i']
    local ptol_`skey'_`scale'_`effect' = point_abs_tol[`i']
    local satol_`skey'_`scale'_`effect' = se_abs_tol[`i']
    local srtol_`skey'_`scale'_`effect' = se_rel_tol[`i']
}
restore

preserve
import delimited using "`qa_dir'/data/mediation_se_covariance.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local scenario = scenario[`i']
    local scale = scale[`i']
    local effect1 = effect1[`i']
    local effect2 = effect2[`i']
    if "`scenario'" == "binary_logit_logit" {
        local skey "b"
    }
    else {
        local skey "c"
    }
    local cov_`skey'_`scale'_`effect1'_`effect2' = covariance[`i']
    local covtol_`skey'_`scale'_`effect1'_`effect2' = cov_abs_tol[`i']
}
restore

tempname pf
tempfile checks
postfile `pf' str8 op str90 label double actual expected tolerance using `checks', replace

**# Binary mediator/outcome: RD scale
capture noisily {
    import delimited using "`qa_dir'/data/mediation_se_binary.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation obe ///
        exposure(x) mediator(m) base_confs(c1 c2) control(0) ///
        commands(m: logit, y: logit) ///
        equations(m: x c1 c2, y: m x c1 c2) ///
        sim(10000) samples(180) seed(202605061) minsim moreMC
}
local rc = _rc
post `pf' ("eq") ("binary logit/logit RD: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    local key "b_rd"
    foreach effect in tce nde nie pm cde {
        local point_expected = `ref_`key'_`effect'_p'
        local se_expected = `ref_`key'_`effect'_s'
        local point_tol = `ptol_`key'_`effect''
        local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
        post `pf' ("abs") ("binary logit/logit RD: `effect' point") (e(`effect')) (`point_expected') (`point_tol')
        post `pf' ("abs") ("binary logit/logit RD: `effect' SE") (e(se_`effect')) (`se_expected') (`se_tol')
    }
    tempname V S
    matrix `V' = e(V)
    matrix `S' = e(se)
    local maxoff = 0
    foreach effect in tce nde nie pm cde {
        local vcol = colnumb(`V', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `vcol' >= . | `scol' >= . {
            post `pf' ("eq") ("binary logit/logit RD: `effect' covariance column exists") (0) (1) (0)
        }
        else {
            local from_v = sqrt(`V'[`vcol', `vcol'])
            local from_se = `S'[1, `scol']
            local diag_tol = max(1e-8, abs(`from_se') * 1e-6)
            post `pf' ("abs") ("binary logit/logit RD: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`from_se') (`diag_tol')
        }
    }
    foreach pair in "tce nde" "tce nie" "tce pm" "tce cde" "nde nie" "nde pm" "nde cde" "nie pm" "nie cde" "pm cde" {
        gettoken e1 e2 : pair
        local c1 = colnumb(`V', "`e1'")
        local c2 = colnumb(`V', "`e2'")
        if `c1' < . & `c2' < . {
            local off = abs(`V'[`c1', `c2'])
            if `off' > `maxoff' local maxoff = `off'
        }
	    }
	    post `pf' ("gtabs") ("binary logit/logit RD: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
	    foreach pair in "tce nde" "tce cde" "nde cde" "nde pm" "pm cde" {
	        gettoken e1 e2 : pair
	        local e1 = strtrim("`e1'")
	        local e2 = strtrim("`e2'")
	        local c1 = colnumb(`V', "`e1'")
	        local c2 = colnumb(`V', "`e2'")
	        if `c1' < . & `c2' < . {
	            local cov_actual = `V'[`c1', `c2']
	            local cov_expected = `cov_`key'_`e1'_`e2''
	            local cov_tol = `covtol_`key'_`e1'_`e2''
	            post `pf' ("abs") ("binary logit/logit RD: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
	        }
	    }
	}

**# Binary mediator/outcome: logOR scale
capture noisily {
    import delimited using "`qa_dir'/data/mediation_se_binary.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation obe ///
        exposure(x) mediator(m) base_confs(c1 c2) control(0) ///
        commands(m: logit, y: logit) ///
        equations(m: x c1 c2, y: m x c1 c2) ///
        sim(10000) samples(180) seed(202605061) minsim moreMC logOR
}
local rc = _rc
post `pf' ("eq") ("binary logit/logit logOR: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    local key "b_logor"
    foreach effect in tce nde nie pm cde {
        local point_expected = `ref_`key'_`effect'_p'
        local se_expected = `ref_`key'_`effect'_s'
        local point_tol = `ptol_`key'_`effect''
        local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
        post `pf' ("abs") ("binary logit/logit logOR: `effect' point") (e(`effect')) (`point_expected') (`point_tol')
        post `pf' ("abs") ("binary logit/logit logOR: `effect' SE") (e(se_`effect')) (`se_expected') (`se_tol')
    }
    tempname V S
    matrix `V' = e(V)
    matrix `S' = e(se)
    local maxoff = 0
    foreach effect in tce nde nie pm cde {
        local vcol = colnumb(`V', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `vcol' >= . | `scol' >= . {
            post `pf' ("eq") ("binary logit/logit logOR: `effect' covariance column exists") (0) (1) (0)
        }
        else {
            local from_v = sqrt(`V'[`vcol', `vcol'])
            local from_se = `S'[1, `scol']
            local diag_tol = max(1e-8, abs(`from_se') * 1e-6)
            post `pf' ("abs") ("binary logit/logit logOR: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`from_se') (`diag_tol')
        }
    }
    foreach pair in "tce nde" "tce nie" "tce pm" "tce cde" "nde nie" "nde pm" "nde cde" "nie pm" "nie cde" "pm cde" {
        gettoken e1 e2 : pair
        local c1 = colnumb(`V', "`e1'")
        local c2 = colnumb(`V', "`e2'")
        if `c1' < . & `c2' < . {
            local off = abs(`V'[`c1', `c2'])
            if `off' > `maxoff' local maxoff = `off'
        }
	    }
	    post `pf' ("gtabs") ("binary logit/logit logOR: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
	    foreach pair in "tce nde" "tce cde" "nde cde" "nde pm" "pm cde" {
	        gettoken e1 e2 : pair
	        local e1 = strtrim("`e1'")
	        local e2 = strtrim("`e2'")
	        local c1 = colnumb(`V', "`e1'")
	        local c2 = colnumb(`V', "`e2'")
	        if `c1' < . & `c2' < . {
	            local cov_actual = `V'[`c1', `c2']
	            local cov_expected = `cov_`key'_`e1'_`e2''
	            local cov_tol = `covtol_`key'_`e1'_`e2''
	            post `pf' ("abs") ("binary logit/logit logOR: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
	        }
	    }
	}

**# Binary mediator/outcome: logRR scale
capture noisily {
    import delimited using "`qa_dir'/data/mediation_se_binary.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation obe ///
        exposure(x) mediator(m) base_confs(c1 c2) control(0) ///
        commands(m: logit, y: logit) ///
        equations(m: x c1 c2, y: m x c1 c2) ///
        sim(10000) samples(180) seed(202605061) minsim moreMC logRR
}
local rc = _rc
post `pf' ("eq") ("binary logit/logit logRR: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    local key "b_logrr"
    foreach effect in tce nde nie pm cde {
        local point_expected = `ref_`key'_`effect'_p'
        local se_expected = `ref_`key'_`effect'_s'
        local point_tol = `ptol_`key'_`effect''
        local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
        post `pf' ("abs") ("binary logit/logit logRR: `effect' point") (e(`effect')) (`point_expected') (`point_tol')
        post `pf' ("abs") ("binary logit/logit logRR: `effect' SE") (e(se_`effect')) (`se_expected') (`se_tol')
    }
    tempname V S
    matrix `V' = e(V)
    matrix `S' = e(se)
    local maxoff = 0
    foreach effect in tce nde nie pm cde {
        local vcol = colnumb(`V', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `vcol' >= . | `scol' >= . {
            post `pf' ("eq") ("binary logit/logit logRR: `effect' covariance column exists") (0) (1) (0)
        }
        else {
            local from_v = sqrt(`V'[`vcol', `vcol'])
            local from_se = `S'[1, `scol']
            local diag_tol = max(1e-8, abs(`from_se') * 1e-6)
            post `pf' ("abs") ("binary logit/logit logRR: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`from_se') (`diag_tol')
        }
    }
    foreach pair in "tce nde" "tce nie" "tce pm" "tce cde" "nde nie" "nde pm" "nde cde" "nie pm" "nie cde" "pm cde" {
        gettoken e1 e2 : pair
        local c1 = colnumb(`V', "`e1'")
        local c2 = colnumb(`V', "`e2'")
        if `c1' < . & `c2' < . {
            local off = abs(`V'[`c1', `c2'])
            if `off' > `maxoff' local maxoff = `off'
        }
	    }
	    post `pf' ("gtabs") ("binary logit/logit logRR: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
	    foreach pair in "tce nde" "tce cde" "nde cde" "nde pm" "pm cde" {
	        gettoken e1 e2 : pair
	        local e1 = strtrim("`e1'")
	        local e2 = strtrim("`e2'")
	        local c1 = colnumb(`V', "`e1'")
	        local c2 = colnumb(`V', "`e2'")
	        if `c1' < . & `c2' < . {
	            local cov_actual = `V'[`c1', `c2']
	            local cov_expected = `cov_`key'_`e1'_`e2''
	            local cov_tol = `covtol_`key'_`e1'_`e2''
	            post `pf' ("abs") ("binary logit/logit logRR: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
	        }
	    }
	}

**# Continuous mediator/outcome: RD scale
capture noisily {
    import delimited using "`qa_dir'/data/mediation_se_continuous.csv", clear varnames(1) asdouble
    gcomp y m x c1 c2, outcome(y) mediation obe ///
        exposure(x) mediator(m) base_confs(c1 c2) control(0) ///
        commands(m: regress, y: regress) ///
        equations(m: x c1 c2, y: m x c1 c2) ///
        sim(10000) samples(180) seed(202605062) minsim moreMC
}
local rc = _rc
post `pf' ("eq") ("continuous linear/linear RD: gcomp execution") (`rc') (0) (0)
if `rc' == 0 {
    local key "c_rd"
    foreach effect in tce nde nie pm cde {
        local point_expected = `ref_`key'_`effect'_p'
        local se_expected = `ref_`key'_`effect'_s'
        local point_tol = `ptol_`key'_`effect''
        local se_tol = max(`satol_`key'_`effect'', abs(`se_expected') * `srtol_`key'_`effect'')
        post `pf' ("abs") ("continuous linear/linear RD: `effect' point") (e(`effect')) (`point_expected') (`point_tol')
        post `pf' ("abs") ("continuous linear/linear RD: `effect' SE") (e(se_`effect')) (`se_expected') (`se_tol')
    }
    tempname V S
    matrix `V' = e(V)
    matrix `S' = e(se)
    local maxoff = 0
    foreach effect in tce nde nie pm cde {
        local vcol = colnumb(`V', "`effect'")
        local scol = colnumb(`S', "`effect'")
        if `vcol' >= . | `scol' >= . {
            post `pf' ("eq") ("continuous linear/linear RD: `effect' covariance column exists") (0) (1) (0)
        }
        else {
            local from_v = sqrt(`V'[`vcol', `vcol'])
            local from_se = `S'[1, `scol']
            local diag_tol = max(1e-8, abs(`from_se') * 1e-6)
            post `pf' ("abs") ("continuous linear/linear RD: sqrt(V[`effect',`effect']) equals e(se)") (`from_v') (`from_se') (`diag_tol')
        }
    }
    foreach pair in "tce nde" "tce nie" "tce pm" "tce cde" "nde nie" "nde pm" "nde cde" "nie pm" "nie cde" "pm cde" {
        gettoken e1 e2 : pair
        local c1 = colnumb(`V', "`e1'")
        local c2 = colnumb(`V', "`e2'")
        if `c1' < . & `c2' < . {
            local off = abs(`V'[`c1', `c2'])
            if `off' > `maxoff' local maxoff = `off'
        }
	    }
	    post `pf' ("gtabs") ("continuous linear/linear RD: e(V) retains nonzero off-diagonal") (`maxoff') (0) (1e-12)
	    foreach pair in "tce nde" "tce cde" "nde cde" "nde pm" "pm cde" {
	        gettoken e1 e2 : pair
	        local e1 = strtrim("`e1'")
	        local e2 = strtrim("`e2'")
	        local c1 = colnumb(`V', "`e1'")
	        local c2 = colnumb(`V', "`e2'")
	        if `c1' < . & `c2' < . {
	            local cov_actual = `V'[`c1', `c2']
	            local cov_expected = `cov_`key'_`e1'_`e2''
	            local cov_tol = `covtol_`key'_`e1'_`e2''
	            post `pf' ("abs") ("continuous linear/linear RD: covariance `e1'-`e2'") (`cov_actual') (`cov_expected') (`cov_tol')
	        }
	    }
	}

postclose `pf'

use `checks', clear
gen double diff = abs(actual - expected)
gen byte passed = .
replace passed = (diff <= tolerance) if op == "abs"
replace passed = (actual == expected) if op == "eq"
replace passed = (abs(actual) > tolerance) if op == "gtabs"

local test_count = _N
quietly count if passed == 1
local pass_count = r(N)
quietly count if passed != 1
local fail_count = r(N)

forvalues i = 1/`=_N' {
    if passed[`i'] == 1 {
        if op[`i'] == "gtabs" {
            display as result "  PASS: " label[`i'] " offdiag=" %10.8f actual[`i'] " min=" %10.8f tolerance[`i']
        }
        else {
            display as result "  PASS: " label[`i'] " actual=" %12.8f actual[`i'] ///
                " expected=" %12.8f expected[`i'] " diff=" %10.8f diff[`i'] ///
                " tol=" %10.8f tolerance[`i']
        }
    }
    else {
        if op[`i'] == "gtabs" {
            display as error "  FAIL: " label[`i'] " offdiag=" %10.8f actual[`i'] " min=" %10.8f tolerance[`i']
        }
        else {
            display as error "  FAIL: " label[`i'] " actual=" %12.8f actual[`i'] ///
                " expected=" %12.8f expected[`i'] " diff=" %10.8f diff[`i'] ///
                " tol=" %10.8f tolerance[`i']
        }
    }
}

display as text ""
display as result "Mediation SE cross-validation results: `pass_count'/`test_count' passed, `fail_count' failed"
if `fail_count' > 0 {
    display "RESULT: crossval_mediation_se tests=`test_count' pass=`pass_count' fail=`fail_count' status=FAIL"
    exit 1
}
display "RESULT: crossval_mediation_se tests=`test_count' pass=`pass_count' fail=`fail_count' status=PASS"
