* crossval_intervention_imputation.do - external oracle QA for stochastic/dynamic rules and imputation
* Manual run from this qa/ directory: stata-mp -b do crossval_intervention_imputation.do
* Fixtures: qa/data/intervention_imputation_*.csv generated by qa/data/generate_intervention_imputation_reference.py

clear all
set varabbrev off
version 16.0

local test_count = 0
local pass_count = 0
local fail_count = 0
local failed_tests ""

local qa_dir "`c(pwd)'"
local pkg_dir = subinstr("`qa_dir'", "/qa", "", 1)
local data_dir "`qa_dir'/data"

capture ado uninstall gcomp
quietly net install gcomp, from("`pkg_dir'") replace
discard

capture noisily shell python3 "`data_dir'/generate_intervention_imputation_reference.py"
if _rc {
    display as error "Python intervention/imputation reference generation failed"
    display "RESULT: crossval_intervention_imputation tests=0 pass=0 fail=1 status=FAIL"
    exit 1
}

preserve
import delimited using "`data_dir'/intervention_imputation_reference.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local scenario = scenario[`i']
    local metric = metric[`i']
    local ref_`scenario'_`metric' = estimate[`i']
    local refse_`scenario'_`metric' = se[`i']
    local tol_`scenario'_`metric' = tolerance_estimate[`i']
    local tolseabs_`scenario'_`metric' = tolerance_se_abs[`i']
    local tolserel_`scenario'_`metric' = tolerance_se_rel[`i']
}
restore

preserve
import delimited using "`data_dir'/intervention_imputation_covariance.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local scenario = scenario[`i']
    local metric1 = metric1[`i']
    local metric2 = metric2[`i']
    local refcov_`scenario'_`metric1'_`metric2' = covariance[`i']
    local tolcov_`scenario'_`metric1'_`metric2' = cov_abs_tol[`i']
}
restore

capture program drop _iix_compare
program define _iix_compare
    version 16.0
    syntax, ACTual(real) EXpected(real) TOLerance(real) LABEL(string)

    local diff = abs(`actual' - `expected')
    noisily display as text "    `label': Stata=" %12.8f `actual' ///
        " Python=" %12.8f `expected' " diff=" %10.8f `diff' ///
        " tol=" %10.8f `tolerance'
    assert `diff' <= `tolerance'
end

capture program drop _iix_extract_dynamic
program define _iix_extract_dynamic, rclass
    version 16.0

    tempname b se V
    matrix `b' = e(b)
    matrix `se' = e(se)
    matrix `V' = e(V)

    local c_dyn = colnumb(`b', "PO1")
    local c_one = colnumb(`b', "PO2")
    local c_zero = colnumb(`b', "PO3")
    if `c_dyn' >= . | `c_one' >= . | `c_zero' >= . {
        display as error "Required PO1/PO2/PO3 columns not found in e(b)"
        exit 498
    }

    return scalar pody = `b'[1, `c_dyn']
    return scalar po1 = `b'[1, `c_one']
    return scalar po0 = `b'[1, `c_zero']
    return scalar rddy0 = `b'[1, `c_dyn'] - `b'[1, `c_zero']
    return scalar rd10 = `b'[1, `c_one'] - `b'[1, `c_zero']

    return scalar se_pody = `se'[1, `c_dyn']
    return scalar se_po1 = `se'[1, `c_one']
    return scalar se_po0 = `se'[1, `c_zero']
    return scalar se_rddy0 = sqrt(`V'[`c_dyn', `c_dyn'] + `V'[`c_zero', `c_zero'] - 2 * `V'[`c_dyn', `c_zero'])
    return scalar se_rd10 = sqrt(`V'[`c_one', `c_one'] + `V'[`c_zero', `c_zero'] - 2 * `V'[`c_one', `c_zero'])

    return scalar vdiag_pody = sqrt(`V'[`c_dyn', `c_dyn'])
    return scalar vdiag_po1 = sqrt(`V'[`c_one', `c_one'])
    return scalar vdiag_po0 = sqrt(`V'[`c_zero', `c_zero'])
    return scalar cov_pody_po0 = `V'[`c_dyn', `c_zero']
    return scalar cov_po1_po0 = `V'[`c_one', `c_zero']
    return scalar cov_abs_sum = abs(`V'[`c_dyn', `c_zero']) + abs(`V'[`c_one', `c_zero'])
end

capture program drop _iix_extract_stochastic
program define _iix_extract_stochastic, rclass
    version 16.0

    tempname b se V
    matrix `b' = e(b)
    matrix `se' = e(se)
    matrix `V' = e(V)

    local c_stoch = colnumb(`b', "PO1")
    local c_one = colnumb(`b', "PO2")
    local c_zero = colnumb(`b', "PO3")
    if `c_stoch' >= . | `c_one' >= . | `c_zero' >= . {
        display as error "Required PO1/PO2/PO3 columns not found in e(b)"
        exit 498
    }

    return scalar postoch = `b'[1, `c_stoch']
    return scalar po1 = `b'[1, `c_one']
    return scalar po0 = `b'[1, `c_zero']
    return scalar rdstoch0 = `b'[1, `c_stoch'] - `b'[1, `c_zero']
    return scalar rd10 = `b'[1, `c_one'] - `b'[1, `c_zero']

    return scalar se_postoch = `se'[1, `c_stoch']
    return scalar se_po1 = `se'[1, `c_one']
    return scalar se_po0 = `se'[1, `c_zero']
    return scalar se_rdstoch0 = sqrt(`V'[`c_stoch', `c_stoch'] + `V'[`c_zero', `c_zero'] - 2 * `V'[`c_stoch', `c_zero'])
    return scalar se_rd10 = sqrt(`V'[`c_one', `c_one'] + `V'[`c_zero', `c_zero'] - 2 * `V'[`c_one', `c_zero'])

    return scalar vdiag_postoch = sqrt(`V'[`c_stoch', `c_stoch'])
    return scalar vdiag_po1 = sqrt(`V'[`c_one', `c_one'])
    return scalar vdiag_po0 = sqrt(`V'[`c_zero', `c_zero'])
    return scalar cov_postoch_po0 = `V'[`c_stoch', `c_zero']
    return scalar cov_po1_po0 = `V'[`c_one', `c_zero']
    return scalar cov_abs_sum = abs(`V'[`c_stoch', `c_zero']) + abs(`V'[`c_one', `c_zero'])
end

capture program drop _iix_extract_mediation
program define _iix_extract_mediation, rclass
    version 16.0

    tempname V se
    matrix `V' = e(V)
    matrix `se' = e(se)

    foreach effect in tce nde nie pm cde {
        local c_`effect' = colnumb(`V', "`effect'")
        if `c_`effect'' >= . {
            display as error "Required `effect' column not found in e(V)"
            exit 498
        }
        return scalar `effect' = e(`effect')
        return scalar se_`effect' = e(se_`effect')
        return scalar vdiag_`effect' = sqrt(`V'[`c_`effect'', `c_`effect''])
    }

    return scalar cov_tce_nde = `V'[`c_tce', `c_nde']
    return scalar cov_tce_cde = `V'[`c_tce', `c_cde']
    return scalar cov_nde_cde = `V'[`c_nde', `c_cde']
    return scalar cov_abs_sum = abs(`V'[`c_tce', `c_nde']) + ///
        abs(`V'[`c_tce', `c_cde']) + abs(`V'[`c_nde', `c_cde'])
end

local stata_boot_reps = 90

**# Stochastic intervention rule
import delimited using "`data_dir'/intervention_imputation_dynamic_data.csv", clear varnames(1) asdouble
quietly count if time == 1
local ns = r(N)

gcomp y l0 a l alag llag id time, outcome(y) ///
    idvar(id) tvar(time) ///
    varyingcovariates(l) fixedcovariates(l0) ///
    laggedvars(alag llag) lagrules(alag: a 1, llag: l 1) ///
    intvars(a) ///
    interventions(a=(runiform()<0.70), a=1, a=0) ///
    eofu minsim ///
    commands(a: logit, y: regress, l: regress) ///
    equations(a: l l0, y: a l l0, l: alag llag l0) ///
    sim(`ns') samples(`stata_boot_reps') seed(20260527)

_iix_extract_stochastic

foreach metric in postoch po1 po0 rdstoch0 rd10 {
    local a_stoch_`metric' = r(`metric')
    local a_stoch_se_`metric' = r(se_`metric')
}
foreach metric in postoch po1 po0 {
    local a_stoch_vd_`metric' = r(vdiag_`metric')
}
local a_stoch_cov_postoch_po0 = r(cov_postoch_po0)
local a_stoch_cov_po1_po0 = r(cov_po1_po0)
local a_stoch_covsum = r(cov_abs_sum)

local ++test_count
capture noisily {
    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "time_varying"
    assert e(N) == `ns'
    assert e(MC_sims) == `ns'
}
if _rc == 0 {
    display as result "  PASS: stochastic rule gcomp metadata"
    local ++pass_count
}
else {
    display as error "  FAIL: stochastic rule gcomp metadata (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' stochastic_metadata"
}

foreach metric in postoch po1 po0 rdstoch0 rd10 {
    local ++test_count
    capture noisily _iix_compare, actual(`a_stoch_`metric'') ///
        expected(`ref_stoch_`metric'') tolerance(`tol_stoch_`metric'') ///
        label("stochastic `metric' point estimate")
    if _rc == 0 {
        display as result "  PASS: stochastic `metric' point estimate"
        local ++pass_count
    }
    else {
        display as error "  FAIL: stochastic `metric' point estimate (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' stochastic_`metric'"
    }
}

foreach metric in postoch po1 po0 rdstoch0 rd10 {
    local se_tol = max(`tolseabs_stoch_`metric'', abs(`refse_stoch_`metric'') * `tolserel_stoch_`metric'')
    local ++test_count
    capture noisily _iix_compare, actual(`a_stoch_se_`metric'') ///
        expected(`refse_stoch_`metric'') tolerance(`se_tol') ///
        label("stochastic `metric' bootstrap SE")
    if _rc == 0 {
        display as result "  PASS: stochastic `metric' bootstrap SE"
        local ++pass_count
    }
    else {
        display as error "  FAIL: stochastic `metric' bootstrap SE (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' stochastic_se_`metric'"
    }
}

foreach metric in postoch po1 po0 {
    local ++test_count
    capture noisily _iix_compare, actual(`a_stoch_vd_`metric'') ///
        expected(`a_stoch_se_`metric'') tolerance(1e-10) ///
        label("stochastic `metric' sqrt(diag(e(V))) vs e(se)")
    if _rc == 0 {
        display as result "  PASS: stochastic `metric' e(V) diagonal matches e(se)"
        local ++pass_count
    }
    else {
        display as error "  FAIL: stochastic `metric' e(V) diagonal mismatch (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' stochastic_vdiag_`metric'"
    }
}

foreach pair in "postoch po0" "po1 po0" {
    gettoken metric1 metric2 : pair
    local metric1 = strtrim("`metric1'")
    local metric2 = strtrim("`metric2'")
    local ++test_count
    capture noisily {
        _iix_compare, actual(`a_stoch_cov_`metric1'_`metric2'') ///
            expected(`refcov_stoch_`metric1'_`metric2'') ///
            tolerance(`tolcov_stoch_`metric1'_`metric2'') ///
            label("stochastic covariance `metric1'-`metric2'")
        assert `a_stoch_covsum' > 1e-12
    }
    if _rc == 0 {
        display as result "  PASS: stochastic covariance `metric1'-`metric2'"
        local ++pass_count
    }
    else {
        display as error "  FAIL: stochastic covariance `metric1'-`metric2' (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' stochastic_cov_`metric1'_`metric2'"
    }
}

**# Dynamic intervention rule
import delimited using "`data_dir'/intervention_imputation_dynamic_data.csv", clear varnames(1) asdouble
quietly count if time == 1
local ns = r(N)

gcomp y l0 a l alag llag id time, outcome(y) ///
    idvar(id) tvar(time) ///
    varyingcovariates(l) fixedcovariates(l0) ///
    laggedvars(alag llag) lagrules(alag: a 1, llag: l 1) ///
    intvars(a) ///
    interventions(a=1 if l>0.15 \ a=0 if l<=0.15, a=1, a=0) ///
    dynamic eofu minsim ///
    commands(a: logit, y: regress, l: regress) ///
    equations(a: l l0, y: a l l0, l: alag llag l0) ///
    sim(`ns') samples(`stata_boot_reps') seed(20260525)

_iix_extract_dynamic

foreach metric in pody po1 po0 rddy0 rd10 {
    local a_dyn_`metric' = r(`metric')
    local a_dyn_se_`metric' = r(se_`metric')
}
foreach metric in pody po1 po0 {
    local a_dyn_vd_`metric' = r(vdiag_`metric')
}
local a_dyn_cov_pody_po0 = r(cov_pody_po0)
local a_dyn_cov_po1_po0 = r(cov_po1_po0)
local a_dyn_covsum = r(cov_abs_sum)

local ++test_count
capture noisily {
    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "time_varying"
    assert e(N) == `ns'
    assert e(MC_sims) == `ns'
}
if _rc == 0 {
    display as result "  PASS: dynamic rule gcomp metadata"
    local ++pass_count
}
else {
    display as error "  FAIL: dynamic rule gcomp metadata (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' dynamic_metadata"
}

foreach metric in pody po1 po0 rddy0 rd10 {
    local ++test_count
    capture noisily _iix_compare, actual(`a_dyn_`metric'') ///
        expected(`ref_dyn_`metric'') tolerance(`tol_dyn_`metric'') ///
        label("dynamic `metric' point estimate")
    if _rc == 0 {
        display as result "  PASS: dynamic `metric' point estimate"
        local ++pass_count
    }
    else {
        display as error "  FAIL: dynamic `metric' point estimate (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' dynamic_`metric'"
    }
}

foreach metric in pody po1 po0 rddy0 rd10 {
    local se_tol = max(`tolseabs_dyn_`metric'', abs(`refse_dyn_`metric'') * `tolserel_dyn_`metric'')
    local ++test_count
    capture noisily _iix_compare, actual(`a_dyn_se_`metric'') ///
        expected(`refse_dyn_`metric'') tolerance(`se_tol') ///
        label("dynamic `metric' bootstrap SE")
    if _rc == 0 {
        display as result "  PASS: dynamic `metric' bootstrap SE"
        local ++pass_count
    }
    else {
        display as error "  FAIL: dynamic `metric' bootstrap SE (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' dynamic_se_`metric'"
    }
}

foreach metric in pody po1 po0 {
    local ++test_count
    capture noisily _iix_compare, actual(`a_dyn_vd_`metric'') ///
        expected(`a_dyn_se_`metric'') tolerance(1e-10) ///
        label("dynamic `metric' sqrt(diag(e(V))) vs e(se)")
    if _rc == 0 {
        display as result "  PASS: dynamic `metric' e(V) diagonal matches e(se)"
        local ++pass_count
    }
    else {
        display as error "  FAIL: dynamic `metric' e(V) diagonal mismatch (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' dynamic_vdiag_`metric'"
    }
}

foreach pair in "pody po0" "po1 po0" {
    gettoken metric1 metric2 : pair
    local metric1 = strtrim("`metric1'")
    local metric2 = strtrim("`metric2'")
    local ++test_count
    capture noisily {
        _iix_compare, actual(`a_dyn_cov_`metric1'_`metric2'') ///
            expected(`refcov_dyn_`metric1'_`metric2'') ///
            tolerance(`tolcov_dyn_`metric1'_`metric2'') ///
            label("dynamic covariance `metric1'-`metric2'")
        assert `a_dyn_covsum' > 1e-12
    }
    if _rc == 0 {
        display as result "  PASS: dynamic covariance `metric1'-`metric2'"
        local ++pass_count
    }
    else {
        display as error "  FAIL: dynamic covariance `metric1'-`metric2' (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' dynamic_cov_`metric1'_`metric2'"
    }
}

**# Imputation path
import delimited using "`data_dir'/intervention_imputation_mediation_data.csv", clear varnames(1) asdouble
quietly count
local nmed = r(N)

gcomp y m x c z, outcome(y) mediation obe ///
    exposure(x) mediator(m) base_confs(c) control(0) ///
    commands(m: regress, y: regress) ///
    equations(m: x c, y: m x c) ///
    impute(m) imp_cmd(m: regress) imp_eq(m: x c z) imp_cycles(2) ///
    sim(4000) samples(`stata_boot_reps') seed(20260526) minsim moreMC

_iix_extract_mediation

foreach metric in tce nde nie pm cde {
    local a_imp_`metric' = r(`metric')
    local a_imp_se_`metric' = r(se_`metric')
    local a_imp_vd_`metric' = r(vdiag_`metric')
}
local a_imp_cov_tce_nde = r(cov_tce_nde)
local a_imp_cov_tce_cde = r(cov_tce_cde)
local a_imp_cov_nde_cde = r(cov_nde_cde)
local a_imp_covsum = r(cov_abs_sum)

local ++test_count
capture noisily {
    assert "`e(cmd)'" == "gcomp"
    assert "`e(analysis_type)'" == "mediation"
    assert "`e(mediation_type)'" == "obe"
    assert e(N) == `nmed'
}
if _rc == 0 {
    display as result "  PASS: imputation gcomp metadata"
    local ++pass_count
}
else {
    display as error "  FAIL: imputation gcomp metadata (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' imputation_metadata"
}

foreach metric in tce nde nie pm cde {
    local ++test_count
    capture noisily _iix_compare, actual(`a_imp_`metric'') ///
        expected(`ref_imp_`metric'') tolerance(`tol_imp_`metric'') ///
        label("imputation `metric' point estimate")
    if _rc == 0 {
        display as result "  PASS: imputation `metric' point estimate"
        local ++pass_count
    }
    else {
        display as error "  FAIL: imputation `metric' point estimate (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' imputation_`metric'"
    }
}

foreach metric in tce nde nie pm cde {
    local se_tol = max(`tolseabs_imp_`metric'', abs(`refse_imp_`metric'') * `tolserel_imp_`metric'')
    local ++test_count
    capture noisily _iix_compare, actual(`a_imp_se_`metric'') ///
        expected(`refse_imp_`metric'') tolerance(`se_tol') ///
        label("imputation `metric' bootstrap SE")
    if _rc == 0 {
        display as result "  PASS: imputation `metric' bootstrap SE"
        local ++pass_count
    }
    else {
        display as error "  FAIL: imputation `metric' bootstrap SE (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' imputation_se_`metric'"
    }
}

foreach metric in tce nde nie pm cde {
    local ++test_count
    capture noisily _iix_compare, actual(`a_imp_vd_`metric'') ///
        expected(`a_imp_se_`metric'') tolerance(1e-10) ///
        label("imputation `metric' sqrt(diag(e(V))) vs e(se)")
    if _rc == 0 {
        display as result "  PASS: imputation `metric' e(V) diagonal matches e(se)"
        local ++pass_count
    }
    else {
        display as error "  FAIL: imputation `metric' e(V) diagonal mismatch (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' imputation_vdiag_`metric'"
    }
}

foreach pair in "tce nde" "tce cde" "nde cde" {
    gettoken metric1 metric2 : pair
    local metric1 = strtrim("`metric1'")
    local metric2 = strtrim("`metric2'")
    local ++test_count
    capture noisily {
        _iix_compare, actual(`a_imp_cov_`metric1'_`metric2'') ///
            expected(`refcov_imp_`metric1'_`metric2'') ///
            tolerance(`tolcov_imp_`metric1'_`metric2'') ///
            label("imputation covariance `metric1'-`metric2'")
        assert `a_imp_covsum' > 1e-12
    }
    if _rc == 0 {
        display as result "  PASS: imputation covariance `metric1'-`metric2'"
        local ++pass_count
    }
    else {
        display as error "  FAIL: imputation covariance `metric1'-`metric2' (error `=_rc')"
        local ++fail_count
        local failed_tests "`failed_tests' imputation_cov_`metric1'_`metric2'"
    }
}

capture program drop _iix_compare
capture program drop _iix_extract_stochastic
capture program drop _iix_extract_dynamic
capture program drop _iix_extract_mediation

display as text ""
display as result "Intervention/imputation cross-validation: `pass_count'/`test_count' passed, `fail_count' failed"
if `fail_count' > 0 {
    display "RESULT: crossval_intervention_imputation tests=`test_count' pass=`pass_count' fail=`fail_count' status=FAIL"
    display as error "FAIL"
    display as error "Failed comparisons:`failed_tests'"
    exit 1
}

display "RESULT: crossval_intervention_imputation tests=`test_count' pass=`pass_count' fail=`fail_count' status=PASS"
display as result "PASS"
