* crossval_longitudinal_extended.do - External longitudinal non-EOFU QA for gcomp
* Manual run from this qa/ directory: stata-mp -b do crossval_longitudinal_extended.do
* Fixtures: qa/data/longitudinal_extended_*.csv generated by qa/data/generate_longitudinal_extended_reference.py

clear all
set varabbrev off
version 16.0

local test_count = 0
local pass_count = 0
local fail_count = 0
local failed_tests ""

local qa_dir "`c(pwd)'"
local pkg_dir = subinstr("`qa_dir'", "/qa", "", 1)
local data_dir "`qa_dir'/data"

do "`qa_dir'/_qa_bootstrap.do"

preserve
import delimited using "`data_dir'/longitudinal_extended_reference.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local metric = metric[`i']
    local ref_`metric' = estimate[`i']
    local refse_`metric' = se[`i']
    local tol_`metric' = tolerance_estimate[`i']
    local tolse_`metric' = tolerance_se[`i']
}
restore

preserve
import delimited using "`data_dir'/longitudinal_extended_covariance.csv", clear varnames(1) asdouble
forvalues i = 1/`=_N' {
    local metric1 = metric1[`i']
    local metric2 = metric2[`i']
    local refcov_`metric1'_`metric2' = covariance[`i']
    local tolcov_`metric1'_`metric2' = tolerance_covariance[`i']
}
restore

capture program drop _gle_compare
program define _gle_compare
    version 16.0
    syntax, ACTual(real) EXpected(real) TOLerance(real) LABEL(string)

    local diff = abs(`actual' - `expected')
    noisily display as text "    `label': Stata=" %12.8f `actual' ///
        " Python=" %12.8f `expected' " diff=" %10.8f `diff' ///
        " tol=" %10.8f `tolerance'
    assert `diff' <= `tolerance'
end

capture program drop _gle_run_survival
program define _gle_run_survival, eclass
    version 16.0

    gcomp y d l a c id time, outcome(y) ///
        idvar(id) tvar(time) ///
        varyingcovariates(l) ///
        fixedcovariates(c) ///
        intvars(a) ///
        interventions(a=1, a=0) ///
        death(d) ///
        commands(d: logit, l: regress, a: logit, y: logit) ///
        equations(d: a c, l: c, a: c l, y: a c) ///
        pooled ///
        msm(logit y a) ///
        sim(720) samples(50) seed(20260519)
end

import delimited using "`data_dir'/longitudinal_extended_survival.csv", clear varnames(1) asdouble
capture noisily _gle_run_survival
if _rc {
    display as error "gcomp longitudinal non-EOFU command failed (error `=_rc')"
    display as error "Failing command is in _gle_run_survival in crossval_longitudinal_extended.do"
    display "RESULT: crossval_longitudinal_extended tests=0 pass=0 fail=1 status=FAIL"
    exit 1
}

assert "`e(cmd)'" == "gcomp"
assert "`e(analysis_type)'" == "time_varying"
assert "`e(msm)'" == "logit y a"

tempname b se V
matrix `b' = e(b)
matrix `se' = e(se)
matrix `V' = e(V)

local c_msm_a = colnumb(`b', "a")
if `c_msm_a' >= . {
    local c_msm_a = colnumb(`b', "a_")
}
local c_msm_cons = colnumb(`b', "_cons")
local c_po1 = colnumb(`b', "PO1")
local c_po2 = colnumb(`b', "PO2")
local c_out1 = colnumb(`b', "out1")
local c_death1 = colnumb(`b', "death1")
local c_out2 = colnumb(`b', "out2")
local c_death2 = colnumb(`b', "death2")

foreach cname in c_msm_a c_msm_cons c_po1 c_po2 c_out1 c_death1 c_out2 c_death2 {
    assert ``cname'' < .
}

local actual_msm_a = `b'[1, `c_msm_a']
local actual_msm_cons = `b'[1, `c_msm_cons']
local actual_po_a1 = `b'[1, `c_po1']
local actual_po_a0 = `b'[1, `c_po2']
local actual_out_a1 = `b'[1, `c_out1']
local actual_out_a0 = `b'[1, `c_out2']
local actual_death_a1 = `b'[1, `c_death1']
local actual_death_a0 = `b'[1, `c_death2']
local actual_out_diff_a1_a0 = `actual_out_a1' - `actual_out_a0'
local actual_death_diff_a1_a0 = `actual_death_a1' - `actual_death_a0'

local actualse_msm_a = `se'[1, `c_msm_a']
local actualse_msm_cons = `se'[1, `c_msm_cons']
local actualse_po_a1 = `se'[1, `c_po1']
local actualse_po_a0 = `se'[1, `c_po2']
local actualse_out_a1 = `se'[1, `c_out1']
local actualse_out_a0 = `se'[1, `c_out2']
local actualse_death_a1 = `se'[1, `c_death1']
local actualse_death_a0 = `se'[1, `c_death2']
local actualse_out_diff_a1_a0 = sqrt(`V'[`c_out1', `c_out1'] + `V'[`c_out2', `c_out2'] - 2 * `V'[`c_out1', `c_out2'])
local actualse_death_diff_a1_a0 = sqrt(`V'[`c_death1', `c_death1'] + `V'[`c_death2', `c_death2'] - 2 * `V'[`c_death1', `c_death2'])

local actualcov_out_a1_out_a0 = `V'[`c_out1', `c_out2']
local actualcov_death_a1_death_a0 = `V'[`c_death1', `c_death2']
local actualcov_msm_a_msm_cons = `V'[`c_msm_a', `c_msm_cons']

**# Point-estimate checks for non-EOFU outputs
local ++test_count
capture noisily {
    foreach metric in po_a1 po_a0 out_a1 out_a0 death_a1 death_a0 out_diff_a1_a0 death_diff_a1_a0 {
        _gle_compare, actual(`actual_`metric'') expected(`ref_`metric'') ///
            tolerance(`tol_`metric'') label("`metric' point estimate")
    }
}
if _rc == 0 {
    display as result "  PASS: non-EOFU PO/out/death point estimates match Python oracle"
    local ++pass_count
}
else {
    display as error "  FAIL: non-EOFU PO/out/death point estimates (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' non_eofu_points"
}

**# MSM point-estimate checks
local ++test_count
capture noisily {
    foreach metric in msm_a msm_cons {
        _gle_compare, actual(`actual_`metric'') expected(`ref_`metric'') ///
            tolerance(`tol_`metric'') label("`metric' point estimate")
    }
}
if _rc == 0 {
    display as result "  PASS: pooled MSM point estimates match Python oracle"
    local ++pass_count
}
else {
    display as error "  FAIL: MSM point estimates (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' msm_points"
}

**# Bootstrap SE checks where practical
local ++test_count
capture noisily {
    foreach metric in po_a1 po_a0 out_a1 out_a0 death_a1 death_a0 out_diff_a1_a0 death_diff_a1_a0 msm_a msm_cons {
        _gle_compare, actual(`actualse_`metric'') expected(`refse_`metric'') ///
            tolerance(`tolse_`metric'') label("`metric' bootstrap SE")
    }
}
if _rc == 0 {
    display as result "  PASS: selected bootstrap SEs agree with Python pooled subject-bootstrap reference"
    local ++pass_count
}
else {
    display as error "  FAIL: selected bootstrap SEs (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' bootstrap_se"
}

**# e(V) diagonal agrees with e(se)
local ++test_count
capture noisily {
    foreach metric in msm_a msm_cons po_a1 po_a0 out_a1 out_a0 death_a1 death_a0 {
        if "`metric'" == "msm_a" local cidx = `c_msm_a'
        else if "`metric'" == "msm_cons" local cidx = `c_msm_cons'
        else if "`metric'" == "po_a1" local cidx = `c_po1'
        else if "`metric'" == "po_a0" local cidx = `c_po2'
        else if "`metric'" == "out_a1" local cidx = `c_out1'
        else if "`metric'" == "out_a0" local cidx = `c_out2'
        else if "`metric'" == "death_a1" local cidx = `c_death1'
        else if "`metric'" == "death_a0" local cidx = `c_death2'

        local from_v = sqrt(`V'[`cidx', `cidx'])
        _gle_compare, actual(`from_v') expected(`actualse_`metric'') ///
            tolerance(1e-10) label("`metric' sqrt(diag(e(V)))")
    }
}
if _rc == 0 {
    display as result "  PASS: e(V) diagonal matches e(se) for longitudinal outputs"
    local ++pass_count
}
else {
    display as error "  FAIL: e(V) diagonal mismatch (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' vdiag"
}

**# Off-diagonal covariance checks
local ++test_count
capture noisily {
    foreach pair in out_a1_out_a0 death_a1_death_a0 msm_a_msm_cons {
        _gle_compare, actual(`actualcov_`pair'') expected(`refcov_`pair'') ///
            tolerance(`tolcov_`pair'') label("cov(`pair')")
    }
}
if _rc == 0 {
    display as result "  PASS: selected off-diagonal covariances agree with Python bootstrap"
    local ++pass_count
}
else {
    display as error "  FAIL: selected off-diagonal covariance checks (error `=_rc')"
    local ++fail_count
    local failed_tests "`failed_tests' covariance"
}

capture program drop _gle_compare
capture program drop _gle_run_survival

display as text ""
display as result "Longitudinal extended cross-validation: `pass_count'/`test_count' passed, `fail_count' failed"
if `fail_count' > 0 {
    display "RESULT: crossval_longitudinal_extended tests=`test_count' pass=`pass_count' fail=`fail_count' status=FAIL"
    display as error "FAIL"
    display as error "Failed comparisons:`failed_tests'"
    exit 1
}

display "RESULT: crossval_longitudinal_extended tests=`test_count' pass=`pass_count' fail=`fail_count' status=PASS"
display as result "PASS"
