#!/usr/bin/env python3
"""
crossval_python.py
Python cross-validation of msm package IPTW weights and treatment effect estimates

Uses: statsmodels (GLM, WLS), numpy, pandas, scipy
Analyzes the same DGP datasets generated by crossval_dgp_generate.do
Exports results to CSV for comparison in Stata
"""

import numpy as np
import pandas as pd
from scipy.special import expit
import statsmodels.api as sm
import statsmodels.formula.api as smf
import os
import warnings
warnings.filterwarnings("ignore")

print("=== PYTHON CROSS-VALIDATION FOR MSM PACKAGE ===")
print(f"numpy: {np.__version__}, pandas: {pd.__version__}, statsmodels: {sm.__version__}")
print()

qa_dir = "/home/tpcopeland/Stata-Tools/msm/qa"
data_dir = os.path.join(qa_dir, "crossval_data")
results_dir = os.path.join(qa_dir, "crossval_results")

# =========================================================================
# DGP 1: Time-varying treatment with confounder feedback
# =========================================================================
print("DGP 1: Time-varying treatment analysis")
print("-" * 40)

dgp1 = pd.read_csv(os.path.join(data_dir, "dgp1_panel.csv"))
print(f"  Loaded: {len(dgp1)} rows, {dgp1['id'].nunique()} individuals")

# --- Replicate msm_weight.ado logic ---
# Denominator: treatment ~ lag_treatment + L + V + period
# For period 0 (no lag): treatment ~ L + V
# Numerator: treatment ~ lag_treatment + V
# For period 0: treatment ~ V

# Period 0 models
p0 = dgp1[dgp1['period'] == 0].copy()
p0_X_d = sm.add_constant(p0[['L', 'V']])
denom_p0 = sm.GLM(p0['treatment'], p0_X_d, family=sm.families.Binomial()).fit()

p0_X_n = sm.add_constant(p0[['V']])
numer_p0 = sm.GLM(p0['treatment'], p0_X_n, family=sm.families.Binomial()).fit()

# Periods > 0 models
plag = dgp1[dgp1['lag_treatment'].notna()].copy()
plag_X_d = sm.add_constant(plag[['lag_treatment', 'L', 'V', 'period']])
denom_lag = sm.GLM(plag['treatment'], plag_X_d, family=sm.families.Binomial()).fit()

plag_X_n = sm.add_constant(plag[['lag_treatment', 'V']])
numer_lag = sm.GLM(plag['treatment'], plag_X_n, family=sm.families.Binomial()).fit()

# Predict probabilities
dgp1['denom_pr'] = np.nan
dgp1['numer_pr'] = np.nan

# Period 0
idx_p0 = dgp1['period'] == 0
dgp1.loc[idx_p0, 'denom_pr'] = denom_p0.predict(sm.add_constant(dgp1.loc[idx_p0, ['L', 'V']]))
dgp1.loc[idx_p0, 'numer_pr'] = numer_p0.predict(sm.add_constant(dgp1.loc[idx_p0, ['V']]))

# Periods > 0
idx_lag = dgp1['lag_treatment'].notna()
dgp1.loc[idx_lag, 'denom_pr'] = denom_lag.predict(
    sm.add_constant(dgp1.loc[idx_lag, ['lag_treatment', 'L', 'V', 'period']]))
dgp1.loc[idx_lag, 'numer_pr'] = numer_lag.predict(
    sm.add_constant(dgp1.loc[idx_lag, ['lag_treatment', 'V']]))

# Period-specific weight ratios
dgp1['w_t'] = np.where(
    dgp1['treatment'] == 1,
    dgp1['numer_pr'] / dgp1['denom_pr'],
    (1 - dgp1['numer_pr']) / (1 - dgp1['denom_pr'])
)

# Cumulative product via log-sum within individuals
dgp1 = dgp1.sort_values(['id', 'period'])
dgp1['log_w'] = np.log(dgp1['w_t'])
dgp1['cum_log_w'] = dgp1.groupby('id')['log_w'].cumsum()
dgp1['py_weight'] = np.exp(dgp1['cum_log_w'])

py_weight_mean = dgp1['py_weight'].mean()
py_weight_sd = dgp1['py_weight'].std()
print(f"  Weight mean: {py_weight_mean:.4f}")
print(f"  Weight SD:   {py_weight_sd:.4f}")

# Weighted GLM (pooled logistic)
# Use statsmodels GLM with frequency weights
# For IPTW, we use the weights as frequency weights in GLM
fit_py = smf.glm("outcome ~ treatment + V + period",
                  data=dgp1,
                  family=sm.families.Binomial(),
                  freq_weights=dgp1['py_weight'].values).fit(
                      cov_type='cluster',
                      cov_kwds={'groups': dgp1['id'].values})

b_py = fit_py.params['treatment']
se_py = fit_py.bse['treatment']
print(f"  Treatment log-OR: {b_py:.4f} (SE: {se_py:.4f})")
print(f"  Treatment OR:     {np.exp(b_py):.4f}")

# Naive estimate
fit_naive = smf.glm("outcome ~ treatment + L + V + period",
                     data=dgp1,
                     family=sm.families.Binomial()).fit()
b_naive = fit_naive.params['treatment']
se_naive = fit_naive.bse['treatment']
print(f"\n  Naive log-OR:     {b_naive:.4f} (SE: {se_naive:.4f})")
print(f"  Naive OR:         {np.exp(b_naive):.4f}")

# =========================================================================
# DGP 2: Point-treatment
# =========================================================================
print(f"\n\nDGP 2: Point-treatment analysis")
print("-" * 40)

dgp2 = pd.read_csv(os.path.join(data_dir, "dgp2_point.csv"))
print(f"  Loaded: {len(dgp2)} rows")

# Propensity score
ps_fit = smf.glm("treatment ~ X1 + X2",
                  data=dgp2,
                  family=sm.families.Binomial()).fit()
dgp2['ps'] = ps_fit.predict()

# Stabilized weights
p_treat = dgp2['treatment'].mean()
dgp2['sw'] = np.where(
    dgp2['treatment'] == 1,
    p_treat / dgp2['ps'],
    (1 - p_treat) / (1 - dgp2['ps'])
)

py_pt_weight_mean = dgp2['sw'].mean()
py_pt_weight_sd = dgp2['sw'].std()
print(f"  Weight mean: {py_pt_weight_mean:.4f}")
print(f"  Weight SD:   {py_pt_weight_sd:.4f}")

# Weighted regression for ATE
fit_pt = smf.wls("Y ~ treatment", data=dgp2, weights=dgp2['sw']).fit(
    cov_type='HC1')
b_pt = fit_pt.params['treatment']
se_pt = fit_pt.bse['treatment']
print(f"  ATE:  {b_pt:.4f} (SE: {se_pt:.4f})")
print(f"  True: 2.000")

# =========================================================================
# Export results
# =========================================================================
print(f"\n\nExporting results...")

results = pd.DataFrame({
    'method': ['py_manual_iptw', 'py_naive', 'py_point_treatment'],
    'weight_mean': [py_weight_mean, np.nan, py_pt_weight_mean],
    'weight_sd': [py_weight_sd, np.nan, py_pt_weight_sd],
    'coef': [b_py, b_naive, b_pt],
    'se': [se_py, se_naive, se_pt],
    'or_hr': [np.exp(b_py), np.exp(b_naive), np.nan]
})

results.to_csv(os.path.join(results_dir, "py_results.csv"), index=False)
print("  Saved: py_results.csv")

# Export individual-level weights for DGP1
weight_export = dgp1[['id', 'period', 'py_weight', 'denom_pr', 'numer_pr']].copy()
weight_export.columns = ['id', 'period', 'py_weight', 'py_denom_pr', 'py_numer_pr']
weight_export.to_csv(os.path.join(results_dir, "py_weights_dgp1.csv"), index=False)
print("  Saved: py_weights_dgp1.csv")

# Export DGP2 weights
pt_export = dgp2[['id', 'ps', 'sw']].copy()
pt_export.columns = ['id', 'py_ps', 'py_sw']
pt_export.to_csv(os.path.join(results_dir, "py_weights_dgp2.csv"), index=False)
print("  Saved: py_weights_dgp2.csv")

print(f"\n=== PYTHON CROSS-VALIDATION COMPLETE ===")
