#!/usr/bin/env Rscript
# crossval_r.R
# R cross-validation of msm package IPTW weights and treatment effect estimates
#
# Uses: ipw (ipwtm for time-varying weights), survey (svyglm for weighted GLM),
#       sandwich (robust SEs), survival
#
# Analyzes the same DGP datasets generated by crossval_dgp_generate.do
# Exports results to CSV for comparison in Stata

library(ipw)
library(survey)
library(sandwich)
library(survival)

cat("=== R CROSS-VALIDATION FOR MSM PACKAGE ===\n")
cat("Date:", format(Sys.time()), "\n\n")

qa_dir <- "/home/tpcopeland/Stata-Tools/msm/qa"
data_dir <- file.path(qa_dir, "crossval_data")
results_dir <- file.path(qa_dir, "crossval_results")

# =========================================================================
# DGP 1: Time-varying treatment with confounder feedback
# =========================================================================
cat("DGP 1: Time-varying treatment analysis\n")
cat("---------------------------------------\n")

dgp1 <- read.csv(file.path(data_dir, "dgp1_panel.csv"))
cat("  Loaded:", nrow(dgp1), "rows,", length(unique(dgp1$id)), "individuals\n")

# --- Method 1: Manual IPTW (matching msm_weight.ado logic exactly) ---
cat("\n  Method 1: Manual IPTW computation\n")

# Denominator model: treatment ~ lag_treatment + L + V + period
# (excluding first period which has no lag)
# First period: treatment ~ L + V
denom_fit_lag <- glm(treatment ~ lag_treatment + L + V + period,
                     data = dgp1[!is.na(dgp1$lag_treatment), ],
                     family = binomial(link = "logit"))
denom_fit_p0 <- glm(treatment ~ L + V,
                     data = dgp1[dgp1$period == 0, ],
                     family = binomial(link = "logit"))

# Numerator model: treatment ~ lag_treatment + V (baseline only)
# First period: treatment ~ V
numer_fit_lag <- glm(treatment ~ lag_treatment + V,
                     data = dgp1[!is.na(dgp1$lag_treatment), ],
                     family = binomial(link = "logit"))
numer_fit_p0 <- glm(treatment ~ V,
                     data = dgp1[dgp1$period == 0, ],
                     family = binomial(link = "logit"))

# Predict probabilities
dgp1$denom_pr <- NA_real_
dgp1$numer_pr <- NA_real_

# Period 0
idx_p0 <- dgp1$period == 0
dgp1$denom_pr[idx_p0] <- predict(denom_fit_p0, newdata = dgp1[idx_p0, ], type = "response")
dgp1$numer_pr[idx_p0] <- predict(numer_fit_p0, newdata = dgp1[idx_p0, ], type = "response")

# Periods > 0
idx_lag <- !is.na(dgp1$lag_treatment)
dgp1$denom_pr[idx_lag] <- predict(denom_fit_lag, newdata = dgp1[idx_lag, ], type = "response")
dgp1$numer_pr[idx_lag] <- predict(numer_fit_lag, newdata = dgp1[idx_lag, ], type = "response")

# Period-specific weight ratios
dgp1$w_t <- ifelse(dgp1$treatment == 1,
                    dgp1$numer_pr / dgp1$denom_pr,
                    (1 - dgp1$numer_pr) / (1 - dgp1$denom_pr))

# Cumulative product within individuals (via log-sum)
dgp1 <- dgp1[order(dgp1$id, dgp1$period), ]
dgp1$log_w <- log(dgp1$w_t)
dgp1$cum_log_w <- ave(dgp1$log_w, dgp1$id, FUN = cumsum)
dgp1$manual_weight <- exp(dgp1$cum_log_w)

r_weight_mean_manual <- mean(dgp1$manual_weight, na.rm = TRUE)
r_weight_sd_manual <- sd(dgp1$manual_weight, na.rm = TRUE)
cat("    Weight mean: ", round(r_weight_mean_manual, 4), "\n")
cat("    Weight SD:   ", round(r_weight_sd_manual, 4), "\n")

# Weighted GLM (pooled logistic) — manual weights
dgp1_design_manual <- svydesign(ids = ~id, weights = ~manual_weight, data = dgp1)
fit_manual <- svyglm(outcome ~ treatment + V + period,
                      design = dgp1_design_manual,
                      family = quasibinomial(link = "logit"))

b_manual <- coef(fit_manual)["treatment"]
se_manual <- sqrt(vcov(fit_manual)["treatment", "treatment"])
cat("    Treatment log-OR: ", round(b_manual, 4), " (SE:", round(se_manual, 4), ")\n")
cat("    Treatment OR:     ", round(exp(b_manual), 4), "\n")

# --- Method 2: ipwtm package ---
cat("\n  Method 2: ipwtm package\n")

# ipwtm needs a specific format
# Denominator: treatment ~ lag_treatment + L + V + period
# Numerator: treatment ~ lag_treatment + V
# Note: ipwtm uses timevar for period, handles first-period separately

tryCatch({
    # ipwtm computes the weights directly
    ipw_result <- ipwtm(
        exposure = treatment,
        family = "binomial",
        link = "logit",
        numerator = ~ V,
        denominator = ~ L + V,
        id = id,
        timevar = period,
        type = "first",
        data = dgp1
    )

    dgp1$ipw_weight <- ipw_result$ipw.weights

    r_weight_mean_ipw <- mean(dgp1$ipw_weight, na.rm = TRUE)
    r_weight_sd_ipw <- sd(dgp1$ipw_weight, na.rm = TRUE)
    cat("    Weight mean: ", round(r_weight_mean_ipw, 4), "\n")
    cat("    Weight SD:   ", round(r_weight_sd_ipw, 4), "\n")

    # Weighted GLM with ipwtm weights
    dgp1_design_ipw <- svydesign(ids = ~id, weights = ~ipw_weight, data = dgp1)
    fit_ipw <- svyglm(outcome ~ treatment + V + period,
                       design = dgp1_design_ipw,
                       family = quasibinomial(link = "logit"))

    b_ipw <- coef(fit_ipw)["treatment"]
    se_ipw <- sqrt(vcov(fit_ipw)["treatment", "treatment"])
    cat("    Treatment log-OR: ", round(b_ipw, 4), " (SE:", round(se_ipw, 4), ")\n")
    cat("    Treatment OR:     ", round(exp(b_ipw), 4), "\n")
}, error = function(e) {
    cat("    ipwtm failed:", e$message, "\n")
    cat("    Using manual weights only\n")
    b_ipw <<- NA_real_
    se_ipw <<- NA_real_
    r_weight_mean_ipw <<- NA_real_
    r_weight_sd_ipw <<- NA_real_
})

# --- Method 3: Naive (biased) estimate for comparison ---
cat("\n  Method 3: Naive GLM (biased reference)\n")
fit_naive <- glm(outcome ~ treatment + L + V + period,
                 data = dgp1,
                 family = binomial(link = "logit"))
b_naive <- coef(fit_naive)["treatment"]
se_naive <- summary(fit_naive)$coefficients["treatment", "Std. Error"]
cat("    Naive log-OR: ", round(b_naive, 4), " (SE:", round(se_naive, 4), ")\n")
cat("    Naive OR:     ", round(exp(b_naive), 4), "\n")

# =========================================================================
# DGP 2: Point-treatment
# =========================================================================
cat("\n\nDGP 2: Point-treatment analysis\n")
cat("-------------------------------\n")

dgp2 <- read.csv(file.path(data_dir, "dgp2_point.csv"))
cat("  Loaded:", nrow(dgp2), "rows\n")

# Propensity score model
ps_fit <- glm(treatment ~ X1 + X2, data = dgp2, family = binomial)
dgp2$ps <- predict(ps_fit, type = "response")

# Stabilized IPTW
p_treat <- mean(dgp2$treatment)
dgp2$sw <- ifelse(dgp2$treatment == 1,
                   p_treat / dgp2$ps,
                   (1 - p_treat) / (1 - dgp2$ps))

r_pt_weight_mean <- mean(dgp2$sw)
r_pt_weight_sd <- sd(dgp2$sw)
cat("  Weight mean: ", round(r_pt_weight_mean, 4), "\n")
cat("  Weight SD:   ", round(r_pt_weight_sd, 4), "\n")

# Weighted regression for ATE
dgp2_design <- svydesign(ids = ~1, weights = ~sw, data = dgp2)
fit_pt <- svyglm(Y ~ treatment, design = dgp2_design)
b_pt <- coef(fit_pt)["treatment"]
se_pt <- sqrt(vcov(fit_pt)["treatment", "treatment"])
cat("  ATE:    ", round(b_pt, 4), " (SE:", round(se_pt, 4), ")\n")
cat("  True:   2.000\n")

# =========================================================================
# Export all results
# =========================================================================
cat("\n\nExporting results...\n")

results <- data.frame(
    method = c("r_manual_iptw", "r_ipwtm", "r_naive", "r_point_treatment"),
    weight_mean = c(r_weight_mean_manual,
                    ifelse(exists("r_weight_mean_ipw"), r_weight_mean_ipw, NA),
                    NA,
                    r_pt_weight_mean),
    weight_sd = c(r_weight_sd_manual,
                  ifelse(exists("r_weight_sd_ipw"), r_weight_sd_ipw, NA),
                  NA,
                  r_pt_weight_sd),
    coef = c(b_manual, ifelse(is.na(b_ipw), NA, b_ipw), b_naive, b_pt),
    se = c(se_manual, ifelse(is.na(se_ipw), NA, se_ipw), se_naive, se_pt),
    or_hr = c(exp(b_manual), ifelse(is.na(b_ipw), NA, exp(b_ipw)), exp(b_naive), NA),
    stringsAsFactors = FALSE
)

write.csv(results, file.path(results_dir, "r_results.csv"), row.names = FALSE)
cat("  Saved: r_results.csv\n")

# Export individual-level weights for DGP1 (for weight comparison)
weight_export <- data.frame(
    id = dgp1$id,
    period = dgp1$period,
    r_manual_weight = dgp1$manual_weight,
    r_denom_pr = dgp1$denom_pr,
    r_numer_pr = dgp1$numer_pr
)
write.csv(weight_export, file.path(results_dir, "r_weights_dgp1.csv"), row.names = FALSE)
cat("  Saved: r_weights_dgp1.csv\n")

# Export individual-level weights for DGP2
pt_export <- data.frame(
    id = dgp2$id,
    r_ps = dgp2$ps,
    r_sw = dgp2$sw
)
write.csv(pt_export, file.path(results_dir, "r_weights_dgp2.csv"), row.names = FALSE)
cat("  Saved: r_weights_dgp2.csv\n")

cat("\n=== R CROSS-VALIDATION COMPLETE ===\n")
cat("Date:", format(Sys.time()), "\n")
