*! _iivw_fit_p Version 4.3.5  2026/10/06
*! predict for iivw_fit: refuses generated design columns that no longer
*! belong to the fit in e(), then hands off to the underlying model's predict.
*! Author: Timothy P Copeland, Karolinska Institutet
*! Program class: nclass

* Why this exists
* ---------------
* iivw_fit builds its own design columns -- categorical-time dummies, time
* powers, splines, categorical dummies, interactions -- under names that
* depend only on position (`_iivw_tcat_1'). A later fit with `replace' can
* reuse such a name for a DIFFERENT column. Stored estimates keep their
* coefficients but not the columns, so after `estimates restore' the
* underlying glm/mixed predict read whatever the column now holds and returned
* changed predictions at rc 0 (audit F03: up to 1.019 on the audit fixture,
* and 50 previously available predictions went missing).
*
* Every column a fit generates is stamped with that fit's token, and e() records
* the token and the columns. A column that is missing, or carries another fit's
* token, means the design this estimate was fitted on is not in memory: refuse,
* rather than predict from a column whose meaning changed.

program define _iivw_fit_p
    version 16.0
    local __iivw_old_varabbrev = c(varabbrev)
    set varabbrev off
    capture noisily {
        if "`e(iivw_cmd)'" != "iivw_fit" | "`e(iivw_predict)'" == "" {
            display as error "last estimates not found"
            error 301
        }
        local __iivw_tok "`e(iivw_design_token)'"
        local __iivw_stale ""
        if "`__iivw_tok'" != "" {
            foreach __iivw_v in `e(iivw_design_vars)' {
                capture confirm variable `__iivw_v', exact
                if _rc {
                    local __iivw_stale "`__iivw_stale' `__iivw_v'(missing)"
                    continue
                }
                local __iivw_vt : char `__iivw_v'[_iivw_fit_token]
                if "`__iivw_vt'" != "`__iivw_tok'" {
                    local __iivw_stale "`__iivw_stale' `__iivw_v'"
                }
            }
        }
        * The token proves a column was generated by this fit; it cannot see
        * an edit to the SOURCE the column was generated from (raw time, a
        * categorical or interaction source). Every generation site records
        * the exact expression it used, so compare each nonmissing generated
        * value in predict's own if/in selection against that expression.
        * Rows outside the selection, and appended rows whose generated
        * columns agree with the fitted expressions, are not refused.
        if "`e(iivw_design_vars)'" != "" & "`__iivw_stale'" == "" {
            local __iivw_native0 `"`0'"'
            * Evaluate the caller's if/in under the caller's own varabbrev,
            * exactly as the native predict below will.
            set varabbrev `__iivw_old_varabbrev'
            syntax [anything] [if] [in] [, *]
            tempvar __iivw_check
            marksample __iivw_check, novarlist
            set varabbrev off
            local 0 `"`__iivw_native0'"'
            local __iivw_j = 0
            foreach __iivw_v in `e(iivw_design_vars)' {
                local ++__iivw_j
                local __iivw_expr "`e(iivw_expr`__iivw_j')'"
                if "`__iivw_expr'" == "" {
                    local __iivw_stale "`__iivw_stale' `__iivw_v'(expression not recorded)"
                    continue
                }
                capture quietly count if `__iivw_check' & !missing(`__iivw_v') & ///
                    `__iivw_v' != (`__iivw_expr')
                if _rc {
                    local __iivw_stale "`__iivw_stale' `__iivw_v'(source unavailable)"
                }
                else if r(N) > 0 {
                    local __iivw_stale "`__iivw_stale' `__iivw_v'(source or value changed)"
                }
            }
        }
        if "`__iivw_stale'" != "" {
            display as error "predict: the design columns of these estimates are no longer in memory"
            display as error "  regenerated, dropped, or their source data edited:`__iivw_stale'"
            display as error "  the coefficients refer to the columns this fit built; predicting"
            display as error "  from columns another fit rebuilt would silently change the result."
            display as error "  Refit this model (or restore the data it was fitted on) first."
            error 459
        }
    }
    local rc = _rc
    set varabbrev `__iivw_old_varabbrev'
    if `rc' exit `rc'

    * Native mixed BLUP/residual/fitted predictions require the native
    * command identity; the public result carries e(cmd)=iivw_fit. Delegate
    * under a temporary native identity, restored on success or error.
    if "`e(iivw_underlying_cmd)'" == "mixed" {
        _iivw_fit_predict_mixed `0'
    }
    else `e(iivw_predict)' `0'
end

capture program drop _iivw_fit_predict_mixed
program define _iivw_fit_predict_mixed, eclass
    version 16.0
    local __iivw_cmd "`e(cmd)'"
    ereturn local cmd "mixed"
    capture noisily `e(iivw_predict)' `0'
    local __iivw_rc = _rc
    ereturn local cmd "`__iivw_cmd'"
    if `__iivw_rc' exit `__iivw_rc'
end
