*! test_finegray_tvc Version 1.0.0  2026/08/24
*! Regression tests for tvc()/tsplit(): piecewise-constant time-varying effects
*! Author: Timothy P Copeland, Karolinska Institutet

* WHY THIS SUITE EXISTS.
*
* tvc(varlist) with tsplit(numlist) lets the coefficient on the named covariates
* differ across intervals of analysis time.  The estimator is Fine & Gray (1999)
* with a deterministic Z(t) -- their sec. 2 (pp. 497-498) admits exactly that,
* and their own analysis (sec. 7, p. 503) fits treatment x t terms -- so what is
* new here is the computation, not the model.  That is also where it can go
* wrong quietly, in three ways, and every test below exists for one of them:
*
*  1. THE PIECEWISE SCAN IS NOT ACTUALLY PIECEWISE.  Running the ordinary scan
*     and merely widening the coefficient vector converges, posts plausible
*     numbers, and is a different estimator.  T01/T02 pin the fit against two
*     INDEPENDENT implementations of the same model: stcrreg's own tvc()/texp()
*     with an indicator time function (J = 2, the only shape one texp() can
*     express), and -- on data with no competing events, where the
*     subdistribution risk set IS the ordinary risk set -- a hand-split
*     episode Cox fit with ibn.interval#c.x terms, which reaches any J.  Both
*     agree on the log-likelihood as well as the coefficients, so a scan that
*     accumulated the right score from the wrong risk sets would still fail.
*
*  2. THE ORDINARY PATH MOVES.  The four right-censoring scans are called
*     UNMODIFIED, once per interval; nothing in them was edited.  T03 is the
*     guard that this stays true: a fit with no tvc() must reproduce values
*     captured from the tree before the feature existed, bit for bit.
*
*  3. THE TIE CONVENTION SILENTLY FLIPS.  Intervals are (cut_j-1, cut_j], so an
*     event exactly ON a boundary belongs to the EARLIER interval.  Every
*     baseline lookup downstream depends on that -- it is what lets the CIF use
*     an ordinary "largest event time <= s" search instead of a left limit.  T04
*     places an event exactly on a boundary and pins the direction, against
*     stcrreg with texp(_t > c) (agrees) and texp(_t >= c) (must not).
*
* Everything else is contract: the coefficient stripe (T05), e() (T06), the
* refit line the bootstrap replays (T07), determinism (T08), the CIF's own
* piecewise accumulation checked by hand against e(basehaz) (T09), the
* time-dependent xb (T10), factor variables (T11), the cost SHAPE rather than
* wall-clock seconds (T12), and every refusal (T13-T20).  The refusals are
* tested because each one keeps an unsourced or underived quantity from being
* reported at rc 0; a fence nobody tests is a fence that rots.

clear all
set varabbrev off
version 16.0

capture log close _all
log using "test_finegray_tvc.log", replace text name(_fgtv)

local qa_dir "`c(pwd)'"
local pkg_dir = regexr("`qa_dir'", "/qa$", "")
capture ado uninstall finegray
quietly net install finegray, from("`pkg_dir'") replace

local test_count = 0
local pass_count = 0
local fail_count = 0

capture program drop _fgtv_result
program define _fgtv_result, rclass
    args rc label
    if `rc' == 0 {
        display as result "  PASS: `label'"
        return scalar pass = 1
        return scalar fail = 0
    }
    else {
        display as error "  FAIL: `label' (rc=`rc')"
        return scalar pass = 0
        return scalar fail = 1
    }
end

* Competing-risks fixture with a genuinely piecewise cause-1 effect: the
* cause-specific hazard of x1 is 0.8 before `tau' and 0 after, generated by
* two-piece inversion so the change point is exact rather than approximate.
* The SUBDISTRIBUTION effect is not equal to that number -- the two hazards are
* different functionals -- so nothing below asserts recovery of 0.8; what the
* fixture buys is a fit in which the interval coefficients genuinely differ.
capture program drop _fgtv_data
program define _fgtv_data
    version 16.0
    args seed nobs
    if "`seed'" == "" local seed 20260824
    if "`nobs'" == "" local nobs 900
    clear
    set seed `seed'
    quietly set obs `nobs'
    gen long id = _n
    gen byte grp = 1 + mod(_n, 3)
    gen double x1 = rnormal()
    gen double x2 = rbinomial(1, 0.4)
    local tau = 0.7
    gen double h1a = 0.6 * exp(0.80 * x1 - 0.50 * x2)
    gen double h1b = 0.6 * exp(0.00 * x1 - 0.50 * x2)
    gen double E   = -ln(runiform())
    gen double tt1 = cond(E <= h1a * `tau', E / h1a, `tau' + (E - h1a * `tau') / h1b)
    gen double tt2 = -ln(runiform()) / (0.35 * exp(0.30 * x1))
    gen double tc  = rexponential(2.0)
    gen double t   = min(tt1, tt2, tc)
    gen byte status = cond(t == tt1, 1, cond(t == tt2, 2, 0))
    gen byte anyev = status != 0
    quietly stset t, failure(anyev == 1) id(id)
end

* Same generator with the competing cause switched off.  With no competing
* events no subject is ever retained in a risk set past its own exit, so the
* subdistribution risk set is the ordinary one and the estimator collapses to
* Cox -- which is what makes the split-episode oracle in T02 legitimate.
capture program drop _fgtv_data_nc
program define _fgtv_data_nc
    version 16.0
    args seed nobs
    if "`seed'" == "" local seed 987654
    if "`nobs'" == "" local nobs 1200
    clear
    set seed `seed'
    quietly set obs `nobs'
    gen long id = _n
    gen double x1 = rnormal()
    gen double x2 = rbinomial(1, 0.4)
    gen double tt1 = -ln(runiform()) / (0.70 * exp(0.60 * x1 - 0.40 * x2))
    gen double tc  = rexponential(1.6)
    gen double t   = min(tt1, tc)
    gen byte status = cond(t == tt1, 1, 0)
    gen byte anyev = status != 0
    quietly stset t, failure(anyev == 1) id(id)
end

* Build the (start, stop] episode split by hand.  NOT stsplit: stsplit blanks
* the stset failure variable on every non-terminal episode, and rebuilding it
* afterwards is the same work with an extra way to get it wrong.  `fail' is 1
* only on the episode that ends at the subject's own exit.
capture program drop _fgtv_split
program define _fgtv_split
    version 16.0
    args c1 c2
    quietly expand 3
    quietly bysort id: gen byte iv = _n
    quietly gen double start = cond(iv == 1, 0, cond(iv == 2, `c1', `c2'))
    quietly gen double _hi   = cond(iv == 1, `c1', cond(iv == 2, `c2', .))
    quietly gen double stop  = cond(missing(_hi), t, min(t, _hi))
    quietly drop if start >= t
    quietly gen byte fail = (status == 1) & (stop == t)
    quietly stset stop, failure(fail == 1) id(id) time0(start)
end

**# T01 equivalence with stcrreg, tvc() texp(_t > c)
local ++test_count
capture noisily {
    _fgtv_data
    * finegray needs every event as an stset failure and splits them with
    * compete()/cause(); stcrreg marks only the cause and names the competing
    * value.  Both fit the same model from the two stsets.
    quietly stset t, failure(status == 1) id(id)
    quietly stcrreg x1 x2, compete(status == 2) tvc(x1) texp(_t > 0.7) nolog
    matrix _sb = e(b)
    local _sll = e(ll)

    quietly stset t, failure(anyev == 1) id(id)
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    matrix _fb = e(b)
    local _fll = e(ll)

    * stcrreg parameterises the second interval as main + tvc; finegray reports
    * the two interval coefficients directly.  Same model, different stripe.
    * reldif(., .) is 0 in Stata, so a missing coefficient would SATISFY every
    * comparison below.  Refuse the missing case first.
    assert !missing(_fb[1,1], _sb[1,2])
    assert reldif(_fb[1,1], _sb[1,2]) < 1e-8
    assert !missing(_fb[1,2], _sb[1,1])
    assert reldif(_fb[1,2], _sb[1,1]) < 1e-8
    * stcrreg's interval-2 coefficient is main + tvc; form it once so the
    * missing guard covers exactly what the comparison consumes.
    local _sb2 = _sb[1,1] + _sb[1,3]
    assert !missing(_fb[1,3], `_sb2')
    assert reldif(_fb[1,3], `_sb2') < 1e-8
    * The log-likelihood is the sharper half of this test: a scan that
    * accumulated a correct-looking score from the wrong risk sets would still
    * land on a different maximum.
    assert !missing(`_fll', `_sll')
    assert reldif(`_fll', `_sll') < 1e-9
}
local _rc = _rc
_fgtv_result `_rc' "T01 tvc()/tsplit() reproduces stcrreg tvc()/texp() (J=2)"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T02 equivalence with a hand-split episode Cox fit (J=3)
local ++test_count
capture noisily {
    _fgtv_data_nc
    quietly finegray x2 x1, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) ///
        nolog norobust
    matrix _fb2 = e(b)
    local _fll2 = e(ll)

    _fgtv_data_nc
    _fgtv_split 0.4 1.0
    * ibn., not i.: every interval carries a real coefficient here because the
    * interaction columns do not sum to a constant.
    quietly stcox x2 ibn.iv#c.x1, breslow nolog
    matrix _cb2 = e(b)
    local _cll2 = e(ll)

    forvalues j = 1/4 {
        assert !missing(_fb2[1, `j'], _cb2[1, `j'])
        assert reldif(_fb2[1, `j'], _cb2[1, `j']) < 1e-7
    }
    assert !missing(`_fll2', `_cll2')
    assert reldif(`_fll2', `_cll2') < 1e-9
}
local _rc = _rc
_fgtv_result `_rc' "T02 three intervals reproduce a split-episode Cox fit"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T03 a fit WITHOUT tvc() has not moved
local ++test_count
capture noisily {
    * The four right-censoring scans are called unmodified when nint <= 1, so
    * the ordinary path must be bit-identical to the tree before tvc() existed.
    * These numbers were captured there, on this fixture, and are pinned rather
    * than recomputed: a regression that moved BOTH the fit and the expectation
    * would pass any self-referential check.
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) nolog basehaz
    assert !missing(_b[x1], _b[x2], e(ll))
    assert reldif(_b[x1], 0.491100467552706) < 1e-13
    assert reldif(_b[x2], -0.374645390653994) < 1e-13
    assert reldif(e(ll), -2000.095085986130016) < 1e-13
    matrix _bh0 = e(basehaz)
    assert !missing(_bh0[5, 2])
    assert reldif(_bh0[5, 2], 0.005650493446466) < 1e-12
}
local _rc = _rc
_fgtv_result `_rc' "T03 a fit without tvc() reproduces the pre-feature values"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T04 an event exactly ON a boundary belongs to the EARLIER interval
local ++test_count
capture noisily {
    _fgtv_data
    * Move one cause event onto the boundary exactly, so the convention is
    * decidable rather than a measure-zero coincidence.
    quietly replace t = 0.7 if _n == 1
    quietly replace status = 1 if _n == 1
    quietly replace anyev = 1 if _n == 1
    quietly count if t == 0.7 & status == 1
    assert !missing(r(N))
    assert r(N) >= 1

    quietly stset t, failure(anyev == 1) id(id)
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    matrix _tb = e(b)

    quietly stset t, failure(status == 1) id(id)
    quietly stcrreg x1 x2, compete(status == 2) tvc(x1) texp(_t > 0.7) nolog
    matrix _tg = e(b)
    quietly stcrreg x1 x2, compete(status == 2) tvc(x1) texp(_t >= 0.7) nolog
    matrix _tge = e(b)

    * (cut_j-1, cut_j] means `_t > 0.7' selects interval 2, so the strict form
    * is the match and the weak form must NOT be.
    assert !missing(_tb[1,2], _tg[1,1], _tge[1,1])
    assert reldif(_tb[1,2], _tg[1,1]) < 1e-8
    assert reldif(_tb[1,2], _tge[1,1]) > 1e-10
}
local _rc = _rc
_fgtv_result `_rc' "T04 an event on a boundary falls in the earlier interval"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T05 the coefficient stripe is the documented one and supports test
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    assert colsof(e(b)) == 4
    local _cn : colnames e(b)
    local _ce : coleq e(b)
    assert "`_cn'" == "x2 x1 x1 x1"
    assert "`_ce'" == "main tvc1 tvc2 tvc3"
    * The Wald test of "is this effect constant?" is the reason the intervals
    * carry separate coefficients rather than base-plus-offsets, and the reason
    * the equation names are plain: [5 < _t <= 10] would not parse.
    quietly test [tvc1]x1 = [tvc2]x1
    assert r(df) == 1
    quietly test [tvc1]x1 = [tvc2]x1 = [tvc3]x1
    assert r(df) == 2
}
local _rc = _rc
_fgtv_result `_rc' "T05 coefficient stripe is main/tvc1..tvcJ and test() works"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T06 the e() contract
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    assert e(n_intervals) == 3
    assert e(k_tvc) == 1
    assert "`e(tvc)'" == "x1"
    assert "`e(tsplit)'" == ".4 1"
    assert "`e(tvc_covariates)'" == "x1"
    assert "`e(tvc_pos)'" == "1"
    assert "`e(designvars)'" == "x1 x2"
    * Cause events per interval, posted so the reader can see what each
    * interval's estimate rests on.
    local _nf "`e(tsplit_nfail)'"
    assert `: word count `_nf'' == 3
    local _tot = 0
    foreach _n of local _nf {
        local _tot = `_tot' + `_n'
    }
    assert `_tot' == e(N_fail)
    * margins is withdrawn: there is no single linear predictor to average.
    assert "`e(marginsok)'" == ""
    * An ordinary fit reports the degenerate shape rather than nothing, so a
    * consumer never has to test for emptiness.
    quietly finegray x1 x2, compete(status) cause(1) nolog
    assert e(n_intervals) == 1
    assert "`e(tvc)'" == ""
}
local _rc = _rc
_fgtv_result `_rc' "T06 e() reports the piecewise shape and the mapping"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T07 e(refitcmd) reproduces e(b) exactly (the Z24 contract)
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    matrix _rb = e(b)
    local _rcmd `"`e(refitcmd)'"'
    * Named, because a dropped fit option does not error in the bootstrap: the
    * refit converges, its covariates still match, the replication is accepted,
    * and the band then describes a DIFFERENT estimator than the point estimate.
    assert strpos(`"`_rcmd'"', "tvc(x1)") > 0
    assert strpos(`"`_rcmd'"', "tsplit(.4 1)") > 0
    quietly `_rcmd'
    matrix _rb2 = e(b)
    mata: st_numscalar("_rdiff", max(abs(st_matrix("_rb") - st_matrix("_rb2"))))
    assert _rdiff == 0
}
local _rc = _rc
_fgtv_result `_rc' "T07 e(refitcmd) replays tvc()/tsplit() and reproduces e(b)"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T08 determinism
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    matrix _d1 = e(b)
    matrix _dv1 = e(V)
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    matrix _d2 = e(b)
    matrix _dv2 = e(V)
    * Each interval re-sorts and re-scans, so the deterministic row-index tie
    * break has to survive being run J times.
    mata: st_numscalar("_dd", max(abs(st_matrix("_d1") - st_matrix("_d2"))))
    mata: st_numscalar("_dvv", max(abs(st_matrix("_dv1") - st_matrix("_dv2"))))
    assert _dd == 0
    assert _dvv == 0
}
local _rc = _rc
_fgtv_result `_rc' "T08 repeated piecewise fits are bit-identical"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T09 predict cif equals a hand-computed piecewise accumulation
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) ///
        nolog basehaz
    quietly finegray_predict double _cifp, cif
    matrix _bh = e(basehaz)
    matrix _cb = e(b)

    * Rebuild CIF(t|z) from the posted baseline and the posted coefficients,
    * with no package code in the path except the step search.  That exception
    * is why this is a CONSISTENCY check on how the pieces are assembled and not
    * an independent one: _finegray_step_core carries the (cut_j-1, cut_j] tie
    * convention, so a build that flipped it moves BOTH sides of the comparison
    * and T09 still passes (verified 2026-08-25 by mutating the convention --
    * T09 green, T04 and the crossval TIES arms red).  T04 is the guard for the
    * convention; this test is the guard for the accumulation.  Formula:
    *   Lambda(t) = sum_j max(0, min(H0(t), H0(cut_j)) - H0(cut_{j-1})) exp(eta_j)
    * H0 is read at the largest event time <= t, which is the same convention
    * (cut_j-1, cut_j] implies.
    tempvar h0 ref
    quietly gen double `h0' = .
    quietly gen double `ref' = .
    mata {
        bh = st_matrix("_bh")
        cb = st_matrix("_cb")
        cuts = (0.4 \ 1.0)
        tt = st_data(., "_t")
        x1v = st_data(., "x1")
        x2v = st_data(., "x2")
        H0 = _finegray_step_core(bh, tt)
        Hc = _finegray_step_core(bh, cuts)
        eta = J(rows(tt), 3, 0)
        for (j = 1; j <= 3; j++) eta[., j] = cb[1,1] :* x2v :+ cb[1, j+1] :* x1v
        lam = J(rows(tt), 1, 0)
        lo = 0
        for (j = 1; j <= 3; j++) {
            hi = (j == 3 ? H0 : (H0 :< Hc[j]) :* H0 :+ (H0 :>= Hc[j]) :* Hc[j])
            piece = (hi :> lo) :* (hi :- lo)
            lam = lam + piece :* exp(eta[., j])
            if (j < 3) lo = Hc[j]
        }
        st_store(., st_varindex(st_local("ref")), 1 :- exp(-lam))
    }
    quietly count if abs(_cifp - `ref') > 1e-12 & _cifp < .
    assert r(N) == 0
    * and it is not trivially the proportional answer
    quietly summarize _cifp
    assert !missing(r(N), r(max))
    assert r(N) > 0 & r(max) > 0 & r(max) < 1
}
local _rc = _rc
_fgtv_result `_rc' "T09 predict cif matches a hand-built piecewise accumulation"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T10 predict xb is time-dependent, and attime() overrides the time
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    matrix _xb = e(b)
    quietly finegray_predict double _xbown, xb
    quietly finegray_predict double _xbe, xb attime(0.2)
    quietly finegray_predict double _xbl, xb attime(3)

    tempvar want
    quietly gen double `want' = _xb[1,1] * x2 + ///
        cond(_t <= 0.7, _xb[1,2], _xb[1,3]) * x1
    quietly count if abs(_xbown - `want') > 1e-12
    assert r(N) == 0
    * A constant evaluation time puts every row in one interval.
    quietly count if abs(_xbe - (_xb[1,1] * x2 + _xb[1,2] * x1)) > 1e-12
    assert r(N) == 0
    quietly count if abs(_xbl - (_xb[1,1] * x2 + _xb[1,3] * x1)) > 1e-12
    assert r(N) == 0
    * attime() exactly on the boundary is the earlier interval, as everywhere
    quietly drop _xbe
    quietly finegray_predict double _xbe, xb attime(0.7)
    quietly count if abs(_xbe - (_xb[1,1] * x2 + _xb[1,2] * x1)) > 1e-12
    assert r(N) == 0
}
local _rc = _rc
_fgtv_result `_rc' "T10 predict xb is interval-aware and attime() overrides it"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T11 factor variables: tvc() frees every column the variable enters
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray i.grp x1, compete(status) cause(1) tvc(grp) tsplit(0.7) nolog
    * i.grp is two design columns; naming the VARIABLE frees both together.
    assert e(k_tvc) == 2
    assert colsof(e(b)) == 5
    assert "`e(tvc_pos)'" == "1 2"
    local _ce : coleq e(b)
    assert "`_ce'" == "main tvc1 tvc1 tvc2 tvc2"
    * and the design columns behind it are named, so the mapping is checkable
    assert "`e(tvc_covariates)'" == "_fg_grp_2 _fg_grp_3"
    * post-estimation survives the factor rebuild path
    quietly finegray_predict double _fvxb, xb
    quietly finegray_predict double _fvcif, cif
    quietly summarize _fvcif
    assert !missing(r(N), r(max))
    assert r(N) > 0 & r(max) < 1
}
local _rc = _rc
_fgtv_result `_rc' "T11 tvc() on a factor variable frees all of its levels"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T12 the cost SHAPE, not the wall clock
local ++test_count
capture noisily {
    * An absolute time gate below ~2x is unfixable on a shared machine, so what
    * is asserted here is the RATIO's stability across n: each interval is one
    * more pass of a linear scan, so tvc/plain must not grow with n.  A rebuild
    * that walked the risk set quadratically inside a boundary would show up as
    * a rising ratio long before it showed up as a failing second count.
    local _rsmall = .
    local _rbig = .
    foreach _n in 4000 16000 {
        _fgtv_data 5150 `_n'
        quietly finegray x1 x2, compete(status) cause(1) nolog
        timer clear 91
        timer on 91
        quietly finegray x1 x2, compete(status) cause(1) nolog
        timer off 91
        quietly timer list 91
        local _tp = r(t91)
        timer clear 92
        timer on 92
        quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.3 0.7 1.4) nolog
        timer off 92
        quietly timer list 92
        local _tt = r(t92)
        local _ratio = `_tt' / `_tp'
        display as text "  n=`_n' plain=`_tp' tvc(J=4)=`_tt' ratio=`_ratio'"
        if `_rsmall' >= . local _rsmall = `_ratio'
        else              local _rbig = `_ratio'
    }
    * Four intervals cost about four passes.  The band is wide because these are
    * seconds on a shared machine; what it forbids is the ratio DOUBLING over a
    * fourfold n, which is what a superlinear rebuild would do.
    assert `_rsmall' > 1 & `_rsmall' < 8
    assert `_rbig' > 1 & `_rbig' < 8
    assert `_rbig' / `_rsmall' < 2
}
local _rc = _rc
_fgtv_result `_rc' "T12 tvc() cost scales like J passes, flat in n"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T13 tvc() and tsplit() are required together
local ++test_count
capture noisily {
    _fgtv_data
    capture finegray x1 x2, compete(status) cause(1) tvc(x1) nolog
    assert _rc == 198
    capture finegray x1 x2, compete(status) cause(1) tsplit(0.5) nolog
    assert _rc == 198
}
local _rc = _rc
_fgtv_result `_rc' "T13 tvc() without tsplit() and tsplit() without tvc() refuse"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T14 tsplit() values must be positive and strictly increasing
local ++test_count
capture noisily {
    _fgtv_data
    capture finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0) nolog
    assert _rc == 198
    capture finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(-1) nolog
    assert _rc != 0
    * numlist's own `ascending' rejects a repeat before the parser sees it; what
    * matters is that neither reaches the engine.
    capture finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.5 0.5) nolog
    assert _rc != 0
    capture finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(1 0.5) nolog
    assert _rc != 0
}
local _rc = _rc
_fgtv_result `_rc' "T14 tsplit() rejects non-positive and non-increasing cuts"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T15 an interval with no cause event is refused, naming the interval
local ++test_count
capture noisily {
    _fgtv_data
    quietly summarize t if status == 1, meanonly
    local _tmax = r(max)
    capture noisily finegray x1 x2, compete(status) cause(1) ///
        tvc(x1) tsplit(`= `_tmax' + 1') nolog
    * r(459), not a dropped coefficient: an unidentified interval silently
    * omitted would change the model without saying so.
    assert _rc == 459
    * A tvc() variable that is not in the model is a specification error too
    capture finegray x1 x2, compete(status) cause(1) tvc(grp) tsplit(0.5) nolog
    assert _rc == 198
}
local _rc = _rc
_fgtv_result `_rc' "T15 an empty interval and an unmodelled tvc() variable refuse"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T16 tvc() refuses delayed entry; nuisance and bstrata() are now allowed
* The unification inverted two thirds of this test.  psi is linear in the score and the
* tvc scan decomposes the score exactly over intervals, so psi decomposes with
* it (_finegray_psi_residuals_pw); crossval_tvc.do gates the result against
* cmprsk::crr's own eq. (7)-(8) variance at 1e-6.  bstrata() reshapes the scan
* on the orthogonal axis and composes mechanically; test_finegray_tvc_bstrata.do
* is its suite.  Delayed entry is unchanged and still refuses -- that fence is
* literature-forced, not an implementation gap.
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.5) ///
        bstrata(grp) nolog
    assert e(converged) == 1
    assert e(k_bstrata) == 3
    assert e(n_intervals) == 2
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.5) ///
        nuisance nolog
    assert e(converged) == 1
    assert "`e(vce_meat)'" == "nuisance_adjusted"
    assert e(n_intervals) == 2

    * Delayed entry: the piecewise scan is the right-censoring scan, and the ZZF
    * branch has no piecewise form.  Reaching it would fit the proportional
    * estimator under a piecewise coefficient stripe at rc 0.
    _fgtv_data
    quietly gen double ent = cond(mod(_n, 4) == 0, 0.05, 0)
    quietly replace ent = 0 if ent >= t
    quietly stset t, failure(anyev == 1) id(id) enter(time ent)
    quietly count if _t0 > 0
    assert !missing(r(N))
    assert r(N) > 0
    capture finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.5) nolog
    assert _rc == 198
}
local _rc = _rc
_fgtv_result `_rc' "T16 tvc() refuses delayed entry; nuisance and bstrata() are allowed"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T17 post-estimation refusals fire and name the alternative
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    * Schoenfeld residuals are defined inside their own interval, so every other
    * interval's block is zero by construction; the table is not a diagnostic.
    capture finegray_predict double _s1, schoenfeld
    assert _rc == 198
    * ...and neither is the test built on them.
    capture finegray_phtest
    assert _rc == 198
    * The analytic CIF interval was refused through v1.3.0 and is DERIVED as of
    * the unification, so both surfaces must now succeed -- and the point estimate must
    * still succeed too, which is what would break if lifting the fence had
    * disturbed the shared parse path.
    capture finegray_predict double _c1, cif ci
    assert _rc == 0
    capture finegray_cif, at(x1=1 x2=0) attime(1) ci nograph
    assert _rc == 0
    capture finegray_cif, at(x1=1 x2=0) attime(1) nograph
    assert _rc == 0
    * attime() is an xb option and only on a piecewise fit
    capture finegray_predict double _c2, cif attime(1)
    assert _rc == 198
    quietly finegray x1 x2, compete(status) cause(1) nolog
    capture finegray_predict double _c3, xb attime(1)
    assert _rc == 198
}
local _rc = _rc
_fgtv_result `_rc' "T17 schoenfeld and phtest refuse; the analytic CIF ci is allowed"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T18 bootstrap CIF intervals work and leave the baseline cache usable
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    quietly finegray_cif, at(x1=1 x2=0) attime(0.3 1.0 2.0) ///
        ci bootstrap(25) seed(11) nograph
    matrix _bt = r(table)
    forvalues r = 1/3 {
        assert _bt[`r', 3] < . & _bt[`r', 3] > 0
        assert _bt[`r', 4] <= _bt[`r', 2]
        assert _bt[`r', 5] >= _bt[`r', 2]
    }
    * Each replication overwrites the single-slot Mata baseline cache; the held
    * fit's entry has to be restored or a later predict on the same fit errors.
    quietly finegray_predict double _bcif, cif
    quietly summarize _bcif
    assert !missing(r(N))
    assert r(N) > 0

    * Per-observation bootstrap intervals travel the same piecewise path.
    quietly finegray_predict double _pcif, cif ci bootstrap(25) seed(11)
    quietly count if _pcif_lci > _pcif & !missing(_pcif_lci)
    assert r(N) == 0
    quietly count if _pcif_uci < _pcif & !missing(_pcif_uci)
    assert r(N) == 0
}
local _rc = _rc
_fgtv_result `_rc' "T18 bootstrap CIF intervals work under tvc()"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T19 the baseline is one curve, and its rebuild uses the piecewise scan
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog basehaz
    matrix _bhA = e(basehaz)
    * The interval structure lives in the linear predictor, not in lambda_0:
    * e(basehaz) keeps the (time, cumhaz) shape and stays monotone across the
    * boundary where the per-interval blocks are stitched together.
    assert colsof(_bhA) == 2
    mata {
        bh = st_matrix("_bhA")
        ok = 1
        for (k = 2; k <= rows(bh); k++) {
            if (bh[k,1] <= bh[k-1,1]) ok = 0
            if (bh[k,2] <  bh[k-1,2]) ok = 0
        }
        st_numscalar("_bhok", ok)
    }
    assert _bhok == 1

    * The cold-cache rebuild path must run the SAME scan the fit ran.  discard
    * wipes the Mata cache, so basecshazard below has to rebuild from the
    * estimation sample; rebuilding with the proportional scan would return a
    * different curve at rc 0.
    quietly finegray_predict double _h0warm, basecshazard
    quietly mata: _finegray_bh_stash()
    mata: _finegray_bh_cache = J(0, 2, .)
    quietly finegray_predict double _h0cold, basecshazard
    quietly mata: _finegray_bh_unstash()
    quietly count if abs(_h0warm - _h0cold) > 1e-10
    assert r(N) == 0
}
local _rc = _rc
_fgtv_result `_rc' "T19 one baseline, and its cold rebuild is the piecewise one"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T20 a constant-effect DGP shows no spurious time variation
local ++test_count
capture noisily {
    * The complement of T01/T02: if the piecewise machinery invented structure,
    * it would show here.  Data generated with a genuinely constant effect must
    * give interval estimates that agree with each other and with the plain fit.
    _fgtv_data_nc 31337 6000
    quietly finegray x2 x1, compete(status) cause(1) nolog
    local _bplain = _b[x1]
    quietly finegray x2 x1, compete(status) cause(1) tvc(x1) tsplit(0.3 0.9) nolog
    quietly test [tvc1]x1 = [tvc2]x1 = [tvc3]x1
    assert !missing(r(p))
    * Not rejected at 1% -- a size-0.01 test on a true null, so this is a
    * property of the estimator and not of the seed at any usable sample size.
    assert r(p) > 0.01
    forvalues j = 1/3 {
        assert abs(_b[tvc`j':x1] - `_bplain') < 0.15
    }
}
local _rc = _rc
_fgtv_result `_rc' "T20 a constant-effect DGP yields no spurious time variation"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T21 factor variables + tvc(): every rebuild path
local ++test_count
capture noisily {
    * The design columns are p wide and e(b) is p' wide, and three separate
    * places used to assert they were equal: the factor-design helper, the CIF
    * profile builder and finegray_predict's own rebuild.  Each of those is a
    * REBUILD path -- reached when the _fg_* columns have been dropped, or when
    * the Mata baseline cache is cold -- so none of them is exercised by an
    * ordinary predict straight after the fit.
    _fgtv_data
    quietly finegray i.grp x1, compete(status) cause(1) tvc(grp) tsplit(0.7) nolog

    * (a) the CIF profile builder
    quietly finegray_cif, at(grp=2 x1=0) attime(0.3 1.0 2.0) nograph
    matrix _fvT = r(table)
    assert rowsof(_fvT) == 3
    forvalues r = 1/3 {
        assert _fvT[`r', 2] > 0 & _fvT[`r', 2] < 1
    }
    * monotone in time, as any CIF must be
    assert _fvT[2, 2] >= _fvT[1, 2]
    assert _fvT[3, 2] >= _fvT[2, 2]

    * (b) the cold-cache baseline rebuild
    quietly finegray_predict double _fvh0w, basecshazard
    quietly mata: _finegray_bh_stash()
    mata: _finegray_bh_cache = J(0, 2, .)
    quietly finegray_predict double _fvh0c, basecshazard
    quietly mata: _finegray_bh_unstash()
    quietly count if abs(_fvh0w - _fvh0c) > 1e-10
    assert r(N) == 0

    * (c) predict after a supported `drop _fg_*'
    quietly finegray_predict double _fvcifA, cif
    quietly drop _fg_grp_*
    quietly finegray_predict double _fvcifB, cif
    quietly count if abs(_fvcifA - _fvcifB) > 1e-12
    assert r(N) == 0
}
local _rc = _rc
_fgtv_result `_rc' "T21 factor variables + tvc() survive every rebuild path"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T22 predict on NEW data, after the estimation sample is gone
local ++test_count
capture noisily {
    * The documented workflow: fit, drop everything, type a covariate profile,
    * predict.  Nothing can be rebuilt then -- the baseline comes from the
    * sequence-keyed Mata cache -- so this is the path where the boundary values
    * Lambda_0(cut_j) MUST come from the same cached curve as the per-row values.
    * Reading them from a second, independently resolved baseline would be a
    * wrong CIF at rc 0 and would show up nowhere else in this suite.
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    quietly finegray_predict double _ndref, cif
    quietly finegray_predict double _ndxbref, xb
    local _r1 = _ndref[1]
    local _rx = _ndxbref[1]
    local _v1 = x1[1]
    local _v2 = x2[1]
    local _vt = _t[1]

    clear
    quietly set obs 3
    quietly gen double x1 = `_v1'
    quietly gen double x2 = `_v2'
    quietly gen double _t = `_vt'
    quietly finegray_predict double _ndcif, cif
    quietly finegray_predict double _ndxb, xb
    * Exactly, not approximately: the same coefficients against the same cached
    * curve at the same time must give the same number to the last bit.
    assert !missing(_ndcif[1], _ndxb[1], `_r1', `_rx')
    assert reldif(_ndcif[1], `_r1') < 1e-14
    assert reldif(_ndxb[1], `_rx') < 1e-14
}
local _rc = _rc
_fgtv_result `_rc' "T22 predict on new data reproduces the in-sample answer"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T23 every covariate time-varying, including a one-covariate model
local ++test_count
capture noisily {
    * nfix == 0 is the shape where the `main' block is empty.  It is also where
    * Mata's 1 x 1 orientation ambiguity bites: with p == 1 and every column
    * time-varying, selectindex() returned a 1 x 0 ROW vector for the
    * (legitimately empty) fixed-column list, and every function declaring it a
    * `real colvector' died r(3203).  A two-covariate all-tvc fit does NOT
    * reproduce that -- p > 1 keeps the orientation unambiguous -- so both are
    * fitted here.
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1 x2) tsplit(0.7) nolog
    assert e(k_tvc) == 2
    assert colsof(e(b)) == 4
    local _ce : coleq e(b)
    assert "`_ce'" == "tvc1 tvc1 tvc2 tvc2"
    quietly finegray_predict double _atxb, xb
    quietly finegray_predict double _atcif, cif
    quietly summarize _atcif
    assert !missing(r(N), r(max))
    assert r(N) > 0 & r(max) < 1

    * one covariate, all of it time-varying
    _fgtv_data
    quietly finegray x1, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    assert e(k_tvc) == 1
    assert e(n_intervals) == 3
    assert colsof(e(b)) == 3
    local _ce1 : coleq e(b)
    assert "`_ce1'" == "tvc1 tvc2 tvc3"
    quietly finegray_predict double _at1xb, xb
    quietly finegray_predict double _at1cif, cif
    quietly summarize _at1cif
    assert !missing(r(N), r(max))
    assert r(N) > 0 & r(max) < 1
    quietly finegray_cif, at(x1=0.5) attime(1 2) nograph
    matrix _atT = r(table)
    assert !missing(_atT[1, 2], _atT[2, 2])
    assert _atT[2, 2] >= _atT[1, 2]
}
local _rc = _rc
_fgtv_result `_rc' "T23 an all-tvc model fits, including with one covariate"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T24 the piecewise likelihood is the nested model's, summed correctly
local ++test_count
capture noisily {
    * Two invariants that need no external tool and that a wrongly-summed set of
    * per-interval passes cannot satisfy at once:
    *
    *  (a) at beta = 0 the linear predictor is 0 in every interval, so the NULL
    *      log-likelihood must equal the proportional fit's -- the J passes
    *      partition the cause events, and a pass that double-counted or dropped
    *      a time would move it.
    *  (b) the proportional model is nested inside the piecewise one, so the
    *      maximized log-likelihood must be strictly HIGHER.  A build that
    *      returned the proportional fit under a wider stripe would tie instead.
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) nolog
    local _p_ll0 = e(ll_0)
    local _p_ll  = e(ll)
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.4 1.0) nolog
    assert !missing(e(ll_0), `_p_ll0')
    * Not bit-identical: the J passes accumulate the same terms in a different
    * floating-point order.  Measured 1.1e-12 relative on this fixture.
    assert reldif(e(ll_0), `_p_ll0') < 1e-11
    assert !missing(e(ll), `_p_ll')
    assert e(ll) > `_p_ll'
    * df_m is the piecewise width, not the design width
    assert e(df_m) == colsof(e(b))
}
local _rc = _rc
_fgtv_result `_rc' "T24 null likelihood matches and the piecewise fit dominates"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# T25 the tvc() CIF table no longer HAS a missing SE column (2026-08-26)
local ++test_count
capture noisily {
    * Read the RENDERED output back.  Through v1.3.0 a tvc() CIF table printed a
    * column of bare dots for the SE and a note underneath explaining that the
    * analytic standard error was not derived.  The unification derives it, so BOTH must
    * be gone: the note must no longer print anywhere, and the rendered table
    * must carry real numbers in the SE column.  Asserting only that the note
    * vanished would also pass if the column had silently gone missing.
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    capture log close _t25
    tempfile _t25log
    log using `"`_t25log'"', replace text name(_t25)
    finegray_cif, at(x1=1 x2=0) attime(0.3 1.0) nograph
    quietly finegray x1 x2, compete(status) cause(1) nolog
    finegray_cif, at(x1=1 x2=0) attime(0.3 1.0) nograph
    log close _t25

    tempname _t25fh
    local _t25n = 0
    file open `_t25fh' using `"`_t25log'"', read text
    file read `_t25fh' line
    while r(eof) == 0 {
        if strpos(`"`line'"', "analytic standard error is not derived") > 0 ///
            local ++_t25n
        file read `_t25fh' line
    }
    file close `_t25fh'
    * The note is now obsolete and must not print on EITHER fit.
    assert `_t25n' == 0
    * and the SE really is there, on the tvc() fit, in r(table)
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    quietly finegray_cif, at(x1=1 x2=0) attime(0.3 1.0) nograph
    tempname _t25T
    matrix `_t25T' = r(table)
    forvalues r = 1/`= rowsof(`_t25T')' {
        assert !missing(`_t25T'[`r', 3])
        assert `_t25T'[`r', 3] > 0
    }
}
local _rc = _rc
capture log close _t25
_fgtv_result `_rc' "T25 the tvc() CIF table has a real SE column and no stale note"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# T26 tvc() ON MULTIPLE-RECORD DATA with zero entry
* -----------------------------------------------------------------------------
* The combination the rest of this suite never fits directly.  T02 builds the
* episode split to feed a hand-split COX oracle, but every finegray fit in the
* suite is on the single-record form, so the multiple-record + tvc() path had
* no direct coverage -- and finegray.ado's own reduction comment used to claim
* the reduction "does not support ... time-varying coefficient effects", which
* would have made that gap a documented refusal instead of an untested path.
*
* It is neither.  tvc()/tsplit() vary beta(t), not the covariate, so the
* multiple-record reduction (one risk-set unit per subject: earliest entry,
* latest exit, final status) leaves the tsplit() grid untouched.  Only DELAYED
* ENTRY is refused with tvc(); on zero-entry episodes that guard reads the
* subject's EARLIEST entry, which is 0, and does not fire.
*
* So the contract is equality, and this test asserts the strong form of it:
* e(b), e(V) and e(ll) must be BIT-IDENTICAL to the single-record fit of the
* same subjects, not merely close.  Then a cold-cache rebuild -- new session
* state, no baseline cache -- must answer from the reduced fit.
local ++test_count
capture noisily {
    * (a) single-record reference
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    tempname _t26bs _t26vs
    matrix `_t26bs' = e(b)
    matrix `_t26vs' = e(V)
    local _t26lls = e(ll)
    local _t26Ns  = e(N)
    assert e(converged) == 1
    assert e(n_intervals) == 2

    * (b) the same subjects as (0, c] episodes, earliest entry 0.  Built by
    * hand rather than with stsplit: stsplit blanks the stset failure variable
    * on every non-terminal episode.  `status' is blanked on the non-terminal
    * episodes too, because it is compete() and finegray refuses a missing
    * compete() value -- so it is set to the censoring value there, and only
    * the terminal episode carries the subject's real event type.
    _fgtv_data
    quietly expand 3
    quietly bysort id: gen byte iv = _n
    quietly gen double start = cond(iv == 1, 0, cond(iv == 2, 0.3, 0.9))
    quietly gen double _hi   = cond(iv == 1, 0.3, cond(iv == 2, 0.9, .))
    quietly gen double stop  = cond(missing(_hi), t, min(t, _hi))
    quietly drop if start >= t
    quietly gen byte fail = (anyev == 1) & (stop == t)
    quietly replace status = 0 if stop != t
    quietly stset stop, failure(fail == 1) id(id) time0(start)

    * it really is multiple-record and really is zero entry
    quietly bysort id: gen long _nrec = _N
    quietly summarize _nrec, meanonly
    assert r(max) > 1
    quietly summarize _t0, meanonly
    assert r(min) == 0
    quietly drop _nrec

    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    assert e(converged) == 1
    assert e(n_intervals) == 2
    * the reduction ran, and landed on the same subject count
    assert e(N) == `_t26Ns'

    tempname _t26bm _t26vm
    matrix `_t26bm' = e(b)
    matrix `_t26vm' = e(V)

    * bit-identity.  mreldif() of a matrix against a missing cell is 0 in
    * Stata, so refuse the missing case before believing the comparison.
    local _t26p = colsof(`_t26bm')
    assert `_t26p' == colsof(`_t26bs')
    forvalues j = 1/`_t26p' {
        assert !missing(`_t26bm'[1, `j'], `_t26bs'[1, `j'])
    }
    assert mreldif(`_t26bm', `_t26bs') == 0
    assert mreldif(`_t26vm', `_t26vs') == 0
    assert !missing(e(ll), `_t26lls')
    assert e(ll) == `_t26lls'

    * equation names survived the reduction unchanged
    local _t26eq : coleq `_t26bm'
    local _t26eq : list uniq _t26eq
    assert "`_t26eq'" == "main tvc1 tvc2"

    * (c) post-estimation off the multiple-record fit, including a COLD-CACHE
    * baseline rebuild: the reduction leaves the fit resting on a derived
    * entry column, and the rebuild has to find the same reduced risk-set
    * units the fit used.  Warm and cold must agree exactly.
    capture drop _xb26
    finegray_predict double _xb26, xb
    quietly count if missing(_xb26) & e(sample)
    assert r(N) == 0

    quietly finegray_predict double _h026w, basecshazard
    quietly mata: _finegray_bh_stash()
    mata: _finegray_bh_cache = J(0, 2, .)
    quietly finegray_predict double _h026c, basecshazard
    quietly mata: _finegray_bh_unstash()
    quietly count if abs(_h026w - _h026c) > 1e-10
    assert r(N) == 0

    quietly finegray_cif, at(x1=0 x2=0) attime(0.4 1.0) nograph
    tempname _t26cif
    matrix `_t26cif' = r(table)
    assert rowsof(`_t26cif') == 2
    assert !missing(`_t26cif'[1, 2], `_t26cif'[2, 2])
    * a CIF is a probability and is nondecreasing in time
    assert `_t26cif'[1, 2] > 0 & `_t26cif'[2, 2] < 1
    assert `_t26cif'[2, 2] >= `_t26cif'[1, 2]
}
local _rc = _rc
_fgtv_result `_rc' ///
    "T26 zero-entry multiple-record tvc() equals the single-record fit bit for bit"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCPSI-01 J = 1 with nuisance is BIT-identical to the plain psi term
* -----------------------------------------------------------------------------
* _finegray_psi_residuals_pw delegates verbatim when nint <= 1, exactly as the
* other four _pw wrappers do, so a fit without tvc() must be untouched.  Asserted
* bit for bit rather than to a tolerance, because "untouched" is the claim.
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) nuisance nolog
    tempname VP BP
    matrix `VP' = e(V)
    matrix `BP' = e(b)
    assert `"`e(vce_meat)'"' == "nuisance_adjusted"
    * a one-interval tvc() fit is refused (tsplit needs a boundary), so the
    * J = 1 path is reached through the ordinary fit; assert the wrapper is
    * genuinely in the call chain by checking the psi term is present at all
    quietly finegray x1 x2, compete(status) cause(1) nolog
    assert !missing(mreldif(e(V), `VP'))
    assert mreldif(e(V), `VP') > 0
    quietly finegray x1 x2, compete(status) cause(1) nuisance nolog
    assert mreldif(e(V), `VP') == 0
    assert mreldif(e(b), `BP') == 0
}
local _rc = _rc
_fgtv_result `_rc' "TVCPSI-01 nuisance without tvc() is bit-identical to the pre-unification term"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCPSI-02 psi under tvc() moves the variance and only the variance
* -----------------------------------------------------------------------------
local ++test_count
capture noisily {
    foreach cuts in "0.7" "0.4 1.0" "0.3 0.7 1.2" {
        _fgtv_data
        quietly finegray x1 x2, compete(status) cause(1) tvc(x1) ///
            tsplit(`cuts') nolog
        tempname VETA BETA
        matrix `VETA' = e(V)
        matrix `BETA' = e(b)
        local nint = e(n_intervals)

        quietly finegray x1 x2, compete(status) cause(1) tvc(x1) ///
            tsplit(`cuts') nuisance nolog
        assert e(n_intervals) == `nint'
        assert `"`e(vce_meat)'"' == "nuisance_adjusted"
        assert colsof(e(V)) == colsof(`VETA')

        forvalues j = 1/`= colsof(`BETA')' {
            assert !missing(`BETA'[1, `j'], e(b)[1, `j'])
            assert reldif(`BETA'[1, `j'], e(b)[1, `j']) < 1e-12
        }
        local moved = 0
        forvalues j = 1/`= colsof(`VETA')' {
            assert !missing(`VETA'[`j', `j'], e(V)[`j', `j'])
            assert e(V)[`j', `j'] > 0
            if reldif(`VETA'[`j', `j'], e(V)[`j', `j']) > 1e-9 local moved = 1
        }
        assert `moved' == 1
    }
}
local _rc = _rc
_fgtv_result `_rc' "TVCPSI-02 nuisance under tvc() moves e(V), never e(b), at J=2/3/4"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCPSI-03 the mask must not invent censoring events (the D3-1 regression)
* -----------------------------------------------------------------------------
* The interval decomposition hands each pass an event vector in which every
* cause event OUTSIDE that interval carries the censoring CODE.  That is right
* for the cause-event set and harmless for the competing set, and it is wrong
* for the censoring counting process N^c, which is what Ghat was estimated from.
* The first implementation of the psi wrapper let the masked vector define N^c
* and so invented (J-1) x #cause-events worth of censoring events.
*
* This test makes the defect visible WITHOUT an R oracle, using a fixture where
* the two readings must differ by construction: no genuinely censored subject at
* all.  With complete follow-up Ghat == 1 everywhere, its influence function is
* identically zero, and psi must be exactly zero -- so the nuisance fit must
* equal the eta-only fit BIT for BIT.  Under the defective reading every
* out-of-interval cause event is a censoring event, N^c is not empty, and psi is
* not zero.  Verified to fail on the defective code.
local ++test_count
capture noisily {
    _fgtv_data
    * complete follow-up: reclassify every censored subject as a competing event
    * so nothing is censored, while cause-1 events (and hence the piecewise
    * effect) survive
    quietly replace status = 2 if status == 0
    quietly replace anyev = 1
    quietly stset t, failure(anyev == 1) id(id)
    quietly count if status == 0
    assert r(N) == 0
    quietly count if status == 1
    assert r(N) > 50

    foreach cuts in "0.7" "0.4 1.0" {
        quietly finegray x1 x2, compete(status) cause(1) tvc(x1) ///
            tsplit(`cuts') nolog
        tempname VNC
        matrix `VNC' = e(V)
        quietly finegray x1 x2, compete(status) cause(1) tvc(x1) ///
            tsplit(`cuts') nuisance nolog
        assert `"`e(vce_meat)'"' == "nuisance_adjusted"
        assert !missing(mreldif(e(V), `VNC'))
        assert mreldif(e(V), `VNC') < 1e-12
    }

    * and the same statement without tvc(), so the test cannot pass because the
    * fixture broke the psi term everywhere
    quietly finegray x1 x2, compete(status) cause(1) nolog
    tempname VNC0
    matrix `VNC0' = e(V)
    quietly finegray x1 x2, compete(status) cause(1) nuisance nolog
    assert mreldif(e(V), `VNC0') < 1e-12
}
local _rc = _rc
_fgtv_result `_rc' "TVCPSI-03 with no censoring the piecewise psi term is exactly zero"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCPSI-04 e(refitcmd) replays a nuisance x tvc fit (Z24 for the new cell)
* -----------------------------------------------------------------------------
local ++test_count
capture noisily {
    _fgtv_data
    foreach spec in "tvc(x1) tsplit(0.7) nuisance" ///
        "tvc(x1) tsplit(0.4 1.0) nuisance" ///
        "tvc(x1) tsplit(0.7) nuisance strata(x2)" {
        quietly finegray x1 x2, compete(status) cause(1) `spec' nolog
        tempname B0
        matrix `B0' = e(b)
        local nint = e(n_intervals)
        local rfc `"`e(refitcmd)'"'
        assert strpos(`"`rfc'"', "tvc(x1)") > 0
        assert strpos(`"`rfc'"', "tsplit(") > 0
        quietly `rfc'
        assert e(n_intervals) == `nint'
        assert colsof(e(b)) == colsof(`B0')
        forvalues j = 1/`= colsof(`B0')' {
            assert !missing(`B0'[1, `j'], e(b)[1, `j'])
            assert reldif(`B0'[1, `j'], e(b)[1, `j']) < 1e-12
        }
    }
}
local _rc = _rc
_fgtv_result `_rc' "TVCPSI-04 e(refitcmd) reproduces e(b) for nuisance x tvc combinations"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCCIF-01 the analytic CIF interval exists, brackets, and says what it is
* -----------------------------------------------------------------------------
* v1.3.0 refused `ci' without bootstrap() after a tvc() fit; the unification derives the
* piecewise influence function (see the header of _finegray_cif_core_pw).  This
* is the shape check: an interval that exists, is positive, contains its own
* point estimate, stays inside (0,1), and reports r(se_method) == "analytic"
* rather than leaving the caller to infer which route ran.
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog

    foreach s in 0.2 0.5 0.9 1.5 {
        quietly finegray_cif, at(x1=0.5 x2=1) attime(`s') ci nograph
        assert `"`r(se_method)'"' == "analytic"
        tempname T
        matrix `T' = r(table)
        assert !missing(`T'[1, 2], `T'[1, 3], `T'[1, 4], `T'[1, 5])
        assert `T'[1, 3] > 0
        assert `T'[1, 4] < `T'[1, 2]
        assert `T'[1, 5] > `T'[1, 2]
        assert `T'[1, 4] > 0
        assert `T'[1, 5] < 1
    }

    * curve mode too -- it evaluates hundreds of horizons through the chunked
    * path, which is where an off-by-one in the chunk arithmetic would show
    quietly finegray_cif, at(x1=0.5 x2=1) ci nograph
    assert `"`r(se_method)'"' == "analytic"
    tempname C
    matrix `C' = r(table)
    assert rowsof(`C') > 20
    forvalues r = 1/`= rowsof(`C')' {
        assert !missing(`C'[`r', 2], `C'[`r', 3])
        assert `C'[`r', 3] >= 0
    }

    * finegray_predict's row-level CI runs on the same fit and agrees with
    * finegray_cif at a row's own time and profile.  Mata-side comparison so no
    * value round-trips through a macro: a truncated decimal literal moves the
    * step lookup by a whole baseline jump and reads as a 2% "defect".
    quietly finegray_predict double _cifq, cif ci
    quietly count if e(sample) & missing(_cifq)
    assert r(N) == 0
    quietly count if e(sample) & !missing(_cifq_lci) & ///
        (_cifq_lci > _cifq | _cifq_uci < _cifq)
    assert r(N) == 0
    * every row without an interval must be one where the CIF is exactly 0,
    * where the cloglog transform is undefined -- the same rule the
    * proportional fit follows
    quietly count if e(sample) & missing(_cifq_lci) & _cifq != 0
    assert r(N) == 0
}
local _rc = _rc
_fgtv_result `_rc' "TVCCIF-01 analytic CIF interval under tvc(): shape, curve mode, predict"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCCIF-02 analytic vs bootstrap, WITH the proportional fit as the control
* -----------------------------------------------------------------------------
* The bootstrap resamples the whole fit and needs no derivation, so it is the
* independent arm.  But the two never agree exactly even for the PROPORTIONAL
* fit, whose analytic CIF variance has shipped and been validated since v1.2.0:
* measured 2026-08-26 on this fixture, the proportional analytic/bootstrap SE
* ratios were 0.984, 0.936, 0.956, 0.951 at t = 0.3/0.5/0.9/1.5.  An influence
* -function SE running a few percent under its bootstrap is a property of the
* estimator, not of the piecewise code.
*
* So the test is a CONTROLLED one: measure both ratios on the same data and
* require the piecewise ratio to sit in the same band as the proportional one.
* Asserting "within 10% of the bootstrap" alone would pass a piecewise variance
* that was simply the proportional one applied to the wrong design, because
* that is also within 10%; requiring it to track the control is what makes the
* comparison about the piecewise term.
local ++test_count
capture noisily {
    _fgtv_data 20260824 2000

    * control arm: the proportional fit
    quietly finegray x1 x2, compete(status) cause(1) nolog
    local pmin = 99
    local pmax = -99
    foreach s in 0.3 0.5 0.9 1.5 {
        quietly finegray_cif, at(x1=0.5 x2=1) attime(`s') ci nograph
        tempname TP
        matrix `TP' = r(table)
        quietly finegray_cif, at(x1=0.5 x2=1) attime(`s') ci ///
            bootstrap(300) seed(4242) nograph
        tempname BP
        matrix `BP' = r(table)
        assert !missing(`TP'[1, 3], `BP'[1, 3])
        assert `BP'[1, 3] > 0
        local rr = `TP'[1, 3] / `BP'[1, 3]
        if `rr' < `pmin' local pmin = `rr'
        if `rr' > `pmax' local pmax = `rr'
    }

    * treatment arm: the piecewise fit
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog
    local tmin = 99
    local tmax = -99
    foreach s in 0.3 0.5 0.9 1.5 {
        quietly finegray_cif, at(x1=0.5 x2=1) attime(`s') ci nograph
        assert `"`r(se_method)'"' == "analytic"
        tempname TT
        matrix `TT' = r(table)
        quietly finegray_cif, at(x1=0.5 x2=1) attime(`s') ci ///
            bootstrap(300) seed(4242) nograph
        assert `"`r(se_method)'"' == "bootstrap"
        tempname BT
        matrix `BT' = r(table)
        assert !missing(`TT'[1, 3], `BT'[1, 3])
        assert `BT'[1, 3] > 0
        local rr = `TT'[1, 3] / `BT'[1, 3]
        if `rr' < `tmin' local tmin = `rr'
        if `rr' > `tmax' local tmax = `rr'
    }

    display as text "    TVCCIF-02: analytic/bootstrap SE ratio -- proportional " ///
        as result %6.4f `pmin' as text " to " as result %6.4f `pmax' ///
        as text ", piecewise " as result %6.4f `tmin' as text " to " ///
        as result %6.4f `tmax'

    * the piecewise ratios must sit in the same band as the control, allowing
    * for the bootstrap's own Monte-Carlo noise at 300 replications (~1/sqrt(2B)
    * = 4%) on each side
    local slack = 0.08
    assert `tmin' > `pmin' - `slack'
    assert `tmax' < `pmax' + `slack'
    * and both must be near 1: a variance that ignored the piecewise structure
    * entirely, or double-counted it, leaves this band
    assert `tmin' > 0.80
    assert `tmax' < 1.20
}
local _rc = _rc
_fgtv_result `_rc' "TVCCIF-02 piecewise analytic CIF SE tracks its bootstrap like the proportional one"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

* -----------------------------------------------------------------------------
**# TVCCIF-03 boundary horizons, and the composed tvc x bstrata analytic SE
* -----------------------------------------------------------------------------
* The boundary is the trap: interval j is (cut_{j-1}, cut_j], so a horizon
* EXACTLY at a cut must be answered entirely from interval 1's coefficients,
* and the SE must be continuous across it rather than jumping.  Evaluated just
* below, at, and just above the cut.
local ++test_count
capture noisily {
    _fgtv_data
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) nolog

    local eps = 1e-9
    quietly finegray_cif, at(x1=0.5 x2=1) attime(`= 0.7 - `eps'') ci nograph
    tempname LO
    matrix `LO' = r(table)
    quietly finegray_cif, at(x1=0.5 x2=1) attime(0.7) ci nograph
    tempname AT
    matrix `AT' = r(table)
    quietly finegray_cif, at(x1=0.5 x2=1) attime(`= 0.7 + `eps'') ci nograph
    tempname HI
    matrix `HI' = r(table)
    forvalues c = 2/3 {
        assert !missing(`LO'[1, `c'], `AT'[1, `c'], `HI'[1, `c'])
    }
    * no baseline event lies in (0.7-eps, 0.7+eps), so all three must agree
    assert reldif(`LO'[1, 2], `AT'[1, 2]) < 1e-10
    assert reldif(`AT'[1, 2], `HI'[1, 2]) < 1e-10
    assert reldif(`LO'[1, 3], `AT'[1, 3]) < 1e-10
    assert reldif(`AT'[1, 3], `HI'[1, 3]) < 1e-10

    * the composed fit gets an analytic SE too, and it must differ by stratum
    * for the same reason the point estimate does
    quietly finegray x1 x2, compete(status) cause(1) tvc(x1) tsplit(0.7) ///
        bstrata(grp) nolog
    local prev = -1
    foreach lev in 1 2 3 {
        quietly finegray_cif, at(x1=0.5 x2=1) bstratum(`lev') attime(0.9) ///
            ci nograph
        assert `"`r(se_method)'"' == "analytic"
        tempname S
        matrix `S' = r(table)
        assert !missing(`S'[1, 2], `S'[1, 3])
        assert `S'[1, 3] > 0
        assert `S'[1, 4] < `S'[1, 2]
        assert `S'[1, 5] > `S'[1, 2]
        if `prev' > 0 assert reldif(`prev', `S'[1, 2]) > 1e-4
        local prev = `S'[1, 2]
    }
}
local _rc = _rc
_fgtv_result `_rc' "TVCCIF-03 analytic CIF SE at interval boundaries and under bstrata()"
local pass_count = `pass_count' + r(pass)
local fail_count = `fail_count' + r(fail)

**# Summary
display as text _newline ///
    "RESULT: test_finegray_tvc tests=`test_count' pass=`pass_count' fail=`fail_count'"
if `fail_count' > 0 {
    display as error "SOME TESTS FAILED"
    log close _fgtv
    exit 1
}
display as result "ALL TESTS PASSED"
log close _fgtv
